// @ts-nocheck
/* GERADO por `pnpm codegen` a partir de contracts/openapi-v1.json. NÃO EDITAR.
   `@ts-nocheck` é deliberado: ver scripts/pos-codegen.mjs. */
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Vitra ERP
 * OpenAPI spec version: v1
 */
import {
  faker
} from '@faker-js/faker';

import type {
  AgendaEventDto,
  DashboardSummaryDto,
  HealthStatus,
  LoginOk,
  PagedResultOfCatalogLookupDto,
  PagedResultOfPartnerDto,
  PagedResultOfProductDto,
  PagedResultOfStockMovementDto,
  PartnerDto,
  ProductDetailDto,
  ProductDto,
  ProductVariantDto,
  ProjectDto,
  ProjectPlanDto,
  ReadinessStatus,
  SessaoAtual,
  StockMovementDto,
  TaskDto,
  TodoDto,
  VinculoDeEmpresa
} from './index.schemas';


export const getHealthResponseMock = (overrideResponse: Partial<Extract<HealthStatus, object>> = {}): HealthStatus => ({status: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getHealthDbResponseMock = (overrideResponse: Partial<Extract<ReadinessStatus, object>> = {}): ReadinessStatus => ({status: faker.string.alpha({length: {min: 10, max: 20}}), detail: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), pendingMigrations: faker.helpers.arrayElement([faker.number.int(), null]), ...overrideResponse})

export const getListCatalogLookupsResponseMock = (overrideResponse: Partial<Extract<PagedResultOfCatalogLookupDto, object>> = {}): PagedResultOfCatalogLookupDto => ({rows: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), kind: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), active: faker.datatype.boolean()})), total: faker.number.int(), ...overrideResponse})

export const getListProductsResponseMock = (overrideResponse: Partial<Extract<PagedResultOfProductDto, object>> = {}): PagedResultOfProductDto => ({rows: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), code: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), active: faker.datatype.boolean()})), total: faker.number.int(), ...overrideResponse})

export const getCreateProductResponseMock = (overrideResponse: Partial<Extract<ProductDto, object>> = {}): ProductDto => ({id: faker.string.uuid(), code: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), active: faker.datatype.boolean(), ...overrideResponse})

export const getGetProductResponseMock = (overrideResponse: Partial<Extract<ProductDetailDto, object>> = {}): ProductDetailDto => ({id: faker.string.uuid(), code: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), active: faker.datatype.boolean(), variants: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), finish: faker.string.alpha({length: {min: 10, max: 20}}), size: faker.string.alpha({length: {min: 10, max: 20}}), active: faker.datatype.boolean(), priceCents: faker.helpers.arrayElement([faker.number.int(), null]), stockQty: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), null]), minStock: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), null])})), ...overrideResponse})

export const getUpdateProductResponseMock = (overrideResponse: Partial<Extract<ProductDto, object>> = {}): ProductDto => ({id: faker.string.uuid(), code: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), active: faker.datatype.boolean(), ...overrideResponse})

export const getCreateVariantResponseMock = (overrideResponse: Partial<Extract<ProductVariantDto, object>> = {}): ProductVariantDto => ({id: faker.string.uuid(), finish: faker.string.alpha({length: {min: 10, max: 20}}), size: faker.string.alpha({length: {min: 10, max: 20}}), active: faker.datatype.boolean(), priceCents: faker.helpers.arrayElement([faker.number.int(), null]), stockQty: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), null]), minStock: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), null]), ...overrideResponse})

export const getUpdateVariantResponseMock = (overrideResponse: Partial<Extract<ProductVariantDto, object>> = {}): ProductVariantDto => ({id: faker.string.uuid(), finish: faker.string.alpha({length: {min: 10, max: 20}}), size: faker.string.alpha({length: {min: 10, max: 20}}), active: faker.datatype.boolean(), priceCents: faker.helpers.arrayElement([faker.number.int(), null]), stockQty: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), null]), minStock: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), null]), ...overrideResponse})

export const getListPartnersResponseMock = (overrideResponse: Partial<Extract<PagedResultOfPartnerDto, object>> = {}): PagedResultOfPartnerDto => ({rows: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), code: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), legalName: faker.string.alpha({length: {min: 10, max: 20}}), tradeName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), document: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), email: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), isCustomer: faker.datatype.boolean(), isSupplier: faker.datatype.boolean(), isProfessional: faker.datatype.boolean(), paymentTerms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), active: faker.datatype.boolean(), registrationActive: faker.datatype.boolean()})), total: faker.number.int(), ...overrideResponse})

export const getCreatePartnerResponseMock = (overrideResponse: Partial<Extract<PartnerDto, object>> = {}): PartnerDto => ({id: faker.string.uuid(), code: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), legalName: faker.string.alpha({length: {min: 10, max: 20}}), tradeName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), document: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), email: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), isCustomer: faker.datatype.boolean(), isSupplier: faker.datatype.boolean(), isProfessional: faker.datatype.boolean(), paymentTerms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), active: faker.datatype.boolean(), registrationActive: faker.datatype.boolean(), ...overrideResponse})

export const getGetPartnerResponseMock = (overrideResponse: Partial<Extract<PartnerDto, object>> = {}): PartnerDto => ({id: faker.string.uuid(), code: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), legalName: faker.string.alpha({length: {min: 10, max: 20}}), tradeName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), document: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), email: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), isCustomer: faker.datatype.boolean(), isSupplier: faker.datatype.boolean(), isProfessional: faker.datatype.boolean(), paymentTerms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), active: faker.datatype.boolean(), registrationActive: faker.datatype.boolean(), ...overrideResponse})

export const getUpdatePartnerResponseMock = (overrideResponse: Partial<Extract<PartnerDto, object>> = {}): PartnerDto => ({id: faker.string.uuid(), code: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), legalName: faker.string.alpha({length: {min: 10, max: 20}}), tradeName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), document: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), email: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), isCustomer: faker.datatype.boolean(), isSupplier: faker.datatype.boolean(), isProfessional: faker.datatype.boolean(), paymentTerms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), active: faker.datatype.boolean(), registrationActive: faker.datatype.boolean(), ...overrideResponse})

export const getLinkPartnerResponseMock = (overrideResponse: Partial<Extract<PartnerDto, object>> = {}): PartnerDto => ({id: faker.string.uuid(), code: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), legalName: faker.string.alpha({length: {min: 10, max: 20}}), tradeName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), document: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), email: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), isCustomer: faker.datatype.boolean(), isSupplier: faker.datatype.boolean(), isProfessional: faker.datatype.boolean(), paymentTerms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), active: faker.datatype.boolean(), registrationActive: faker.datatype.boolean(), ...overrideResponse})

export const getCreateStockMovementResponseMock = (overrideResponse: Partial<Extract<StockMovementDto, object>> = {}): StockMovementDto => ({id: faker.string.uuid(), variantId: faker.string.uuid(), delta: faker.number.float({fractionDigits: 2}), balanceAfter: faker.number.float({fractionDigits: 2}), reason: faker.string.alpha({length: {min: 10, max: 20}}), occurredAt: faker.date.past().toISOString().slice(0, 19) + 'Z', employeeId: faker.helpers.arrayElement([faker.string.uuid(), null]), ...overrideResponse})

export const getListStockMovementsResponseMock = (overrideResponse: Partial<Extract<PagedResultOfStockMovementDto, object>> = {}): PagedResultOfStockMovementDto => ({rows: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), variantId: faker.string.uuid(), delta: faker.number.float({fractionDigits: 2}), balanceAfter: faker.number.float({fractionDigits: 2}), reason: faker.string.alpha({length: {min: 10, max: 20}}), occurredAt: faker.date.past().toISOString().slice(0, 19) + 'Z', employeeId: faker.helpers.arrayElement([faker.string.uuid(), null])})), total: faker.number.int(), ...overrideResponse})

export const getAuthLoginResponseMock = (overrideResponse: Partial<Extract<LoginOk, object>> = {}): LoginOk => ({mustChangePassword: faker.datatype.boolean(), ...overrideResponse})

export const getAuthMeResponseMock = (overrideResponse: Partial<Extract<SessaoAtual, object>> = {}): SessaoAtual => ({organizationId: faker.string.uuid(), employeeId: faker.string.uuid(), activeTenantId: faker.helpers.arrayElement([faker.string.uuid(), null]), expiresAt: faker.date.past().toISOString().slice(0, 19) + 'Z', mustChangePassword: faker.datatype.boolean(), displayName: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), ...overrideResponse})

export const getAuthTenantsResponseMock = (): VinculoDeEmpresa[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({tenantId: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.string.alpha({length: {min: 10, max: 20}}), features: faker.helpers.arrayElements(['suppliers','professionals','employees'] as const)})))

export const getGetDashboardSummaryResponseMock = (overrideResponse: Partial<Extract<DashboardSummaryDto, object>> = {}): DashboardSummaryDto => ({openQuotes: faker.number.int(), openQuotesDueThisWeek: faker.number.int(), incomingOrders: faker.number.int(), incomingOrdersToday: faker.number.int(), criticalStockItems: faker.number.int(), monthSalesCents: faker.number.int(), previousMonthSalesCents: faker.number.int(), ...overrideResponse})

export const getListAgendaEventsResponseMock = (): AgendaEventDto[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), startsAt: faker.date.past().toISOString().slice(0, 19) + 'Z', title: faker.string.alpha({length: {min: 10, max: 20}}), context: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), kind: faker.helpers.arrayElement(['delivery','quote','meeting','payment'] as const)})))

export const getListTasksResponseMock = (): TaskDto[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), status: faker.helpers.arrayElement(['todo','doing','review','done'] as const), priority: faker.helpers.arrayElement(['high','medium','low'] as const), dueOn: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), null]), undefined]), commentCount: faker.number.int(), attachmentCount: faker.number.int(), assignees: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), initials: faker.string.alpha({length: {min: 10, max: 20}})}))})))

export const getCreateTaskResponseMock = (overrideResponse: Partial<Extract<TaskDto, object>> = {}): TaskDto => ({id: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), status: faker.helpers.arrayElement(['todo','doing','review','done'] as const), priority: faker.helpers.arrayElement(['high','medium','low'] as const), dueOn: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), null]), undefined]), commentCount: faker.number.int(), attachmentCount: faker.number.int(), assignees: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), initials: faker.string.alpha({length: {min: 10, max: 20}})})), ...overrideResponse})

export const getPatchTaskResponseMock = (overrideResponse: Partial<Extract<TaskDto, object>> = {}): TaskDto => ({id: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), status: faker.helpers.arrayElement(['todo','doing','review','done'] as const), priority: faker.helpers.arrayElement(['high','medium','low'] as const), dueOn: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), null]), undefined]), commentCount: faker.number.int(), attachmentCount: faker.number.int(), assignees: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), initials: faker.string.alpha({length: {min: 10, max: 20}})})), ...overrideResponse})

export const getListTodosResponseMock = (): TodoDto[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), done: faker.datatype.boolean()})))

export const getPatchTodoResponseMock = (overrideResponse: Partial<Extract<TodoDto, object>> = {}): TodoDto => ({id: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), done: faker.datatype.boolean(), ...overrideResponse})

export const getListProjectsResponseMock = (): ProjectDto[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(['active','proposed','closed'] as const)})))

export const getGetProjectPlanResponseMock = (overrideResponse: Partial<Extract<ProjectPlanDto, object>> = {}): ProjectPlanDto => ({projectId: faker.string.uuid(), phases: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), startsOn: faker.date.past().toISOString().slice(0, 10), endsOn: faker.date.past().toISOString().slice(0, 10), items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), label: faker.string.alpha({length: {min: 10, max: 20}}), kind: faker.helpers.arrayElement(['task','order','delivery'] as const), startsOn: faker.date.past().toISOString().slice(0, 10), endsOn: faker.date.past().toISOString().slice(0, 10), progressPercent: faker.number.int()}))})), ...overrideResponse})

