// @ts-nocheck
/* GERADO por `pnpm codegen` a partir de contracts/openapi-v1.json. NÃO EDITAR.
   `@ts-nocheck` é deliberado: ver scripts/pos-codegen.mjs. */
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Vitra ERP
 * OpenAPI spec version: v1
 */
export interface CatalogLookupDto {
  id: string;
  kind: string;
  name: string;
  active: boolean;
}

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}

export interface HealthStatus {
  status: string;
}

export interface LoginFalhou {
  detail: string;
}

export interface LoginOk {
  mustChangePassword: boolean;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface PagedResultOfCatalogLookupDto {
  rows: CatalogLookupDto[];
  total: number;
}

export interface PartnerDto {
  id: string;
  /** @nullable */
  code: string | null;
  legalName: string;
  /** @nullable */
  tradeName: string | null;
  /** @nullable */
  document: string | null;
  /** @nullable */
  email: string | null;
  isCustomer: boolean;
  isSupplier: boolean;
  isProfessional: boolean;
  /** @nullable */
  paymentTerms: string | null;
  active: boolean;
  registrationActive: boolean;
}

export interface PagedResultOfPartnerDto {
  rows: PartnerDto[];
  total: number;
}

export interface ProductDto {
  id: string;
  code: string;
  description: string;
  active: boolean;
}

export interface PagedResultOfProductDto {
  rows: ProductDto[];
  total: number;
}

export interface StockMovementDto {
  id: string;
  variantId: string;
  delta: number;
  balanceAfter: number;
  reason: string;
  occurredAt: string;
  /** @nullable */
  employeeId: string | null;
}

export interface PagedResultOfStockMovementDto {
  rows: StockMovementDto[];
  total: number;
}

export interface PartnerLinkRequest {
  /** @nullable */
  code: string | null;
  /** @nullable */
  paymentTerms: string | null;
  /** @nullable */
  active: boolean | null;
}

export interface PartnerWriteRequest {
  /** @nullable */
  document: string | null;
  /** @nullable */
  legalName: string | null;
  /** @nullable */
  tradeName: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  isCustomer: boolean | null;
  /** @nullable */
  isSupplier: boolean | null;
  /** @nullable */
  isProfessional: boolean | null;
  /** @nullable */
  code: string | null;
  /** @nullable */
  paymentTerms: string | null;
  /** @nullable */
  active: boolean | null;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
}

export interface ProductVariantDto {
  id: string;
  finish: string;
  size: string;
  active: boolean;
  /** @nullable */
  priceCents: number | null;
  /** @nullable */
  stockQty: number | null;
  /** @nullable */
  minStock: number | null;
}

export interface ProductDetailDto {
  id: string;
  code: string;
  description: string;
  active: boolean;
  variants: ProductVariantDto[];
}

export interface ProductWriteRequest {
  /** @nullable */
  code: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  active: boolean | null;
}

export interface ReadinessStatus {
  status: string;
  /** @nullable */
  detail: string | null;
  /** @nullable */
  pendingMigrations: number | null;
}

export interface SessaoAtual {
  organizationId: string;
  employeeId: string;
  /** @nullable */
  activeTenantId: string | null;
  expiresAt: string;
  mustChangePassword: boolean;
  /**
     * Proposto. Como o operador se chama na tela — a saudação do Dashboard. `null` quando o servidor não sabe: a tela então cumprimenta sem nome, em vez de exibir e-mail ou id, que é identificador de sistema e não nome de gente.
     * @nullable
     */
  displayName?: string | null;
}

export interface StockMovementRequest {
  /** @nullable */
  delta: number | null;
  /** @nullable */
  reason: string | null;
}

export interface TrocarEmpresaRequest {
  tenantId: string;
}

export interface VariantWriteRequest {
  /** @nullable */
  finish: string | null;
  /** @nullable */
  size: string | null;
  /** @nullable */
  active: boolean | null;
  /** @nullable */
  priceCents: number | null;
  /** @nullable */
  minStock: number | null;
}

export type VinculoDeEmpresaFeaturesItem = typeof VinculoDeEmpresaFeaturesItem[keyof typeof VinculoDeEmpresaFeaturesItem];


export const VinculoDeEmpresaFeaturesItem = {
  suppliers: 'suppliers',
  professionals: 'professionals',
  employees: 'employees',
} as const;

export interface VinculoDeEmpresa {
  tenantId: string;
  name: string;
  role: string;
  /** Proposto. Recursos CONTRATADOS por esta empresa — o que ela opera, não o que o usuário pode fazer nela (isso é `role`). Conjunto fechado; valor fora dele é ignorado pelo cliente. Sempre presente: empresa sem recurso opcional devolve `[]`, nunca omite o campo — ausência viraria 'não sei' e o front teria de adivinhar entre esconder tudo e mostrar tudo. */
  features: VinculoDeEmpresaFeaturesItem[];
}

/**
 * Proposto. Os quatro números da faixa de KPI. Dinheiro em CENTAVOS, inteiro — a regra do repo vale no contrato.
 */
export interface DashboardSummaryDto {
  /** Orçamentos abertos. */
  openQuotes: number;
  /** Destes, quantos vencem nos próximos 7 dias. */
  openQuotesDueThisWeek: number;
  /** Pedidos de compra a receber. */
  incomingOrders: number;
  /** Destes, quantos com previsão para hoje. */
  incomingOrdersToday: number;
  /** Variantes com saldo abaixo do mínimo. */
  criticalStockItems: number;
  /** Vendas do mês corrente, em centavos. */
  monthSalesCents: number;
  /** Vendas do mês anterior fechado, em centavos. O front deriva a variação dos dois — percentual pronto no DTO seria número que ninguém consegue conferir na tela. */
  previousMonthSalesCents: number;
}

/**
 * Conjunto fechado — é ele que dá a cor da barra e a legenda do calendário.
 */
export type AgendaEventDtoKind = typeof AgendaEventDtoKind[keyof typeof AgendaEventDtoKind];


export const AgendaEventDtoKind = {
  delivery: 'delivery',
  quote: 'quote',
  meeting: 'meeting',
  payment: 'payment',
} as const;

/**
 * Proposto. Um compromisso da agenda.
 */
export interface AgendaEventDto {
  id: string;
  /** Início, com hora (ISO 8601). */
  startsAt: string;
  title: string;
  /**
     * A quem o compromisso se refere (cliente, obra, fornecedor).
     * @nullable
     */
  context?: string | null;
  /** Conjunto fechado — é ele que dá a cor da barra e a legenda do calendário. */
  kind: AgendaEventDtoKind;
}

/**
 * Proposto. Quem responde pela tarefa.
 */
export interface TaskAssigneeDto {
  id: string;
  name: string;
  /** As iniciais que o avatar mostra. Vêm do servidor porque quem sabe partir 'Maria da Silva' em 'MS' é quem guarda o nome — o front partindo string faria 'DS' em nome com preposição. */
  initials: string;
}

/**
 * A coluna do quadro.
 */
export type TaskDtoStatus = typeof TaskDtoStatus[keyof typeof TaskDtoStatus];


export const TaskDtoStatus = {
  todo: 'todo',
  doing: 'doing',
  review: 'review',
  done: 'done',
} as const;

export type TaskDtoPriority = typeof TaskDtoPriority[keyof typeof TaskDtoPriority];


export const TaskDtoPriority = {
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;

/**
 * Proposto. Um cartão do quadro.
 */
export interface TaskDto {
  id: string;
  title: string;
  /** @nullable */
  description?: string | null;
  /** A coluna do quadro. */
  status: TaskDtoStatus;
  priority: TaskDtoPriority;
  /**
     * Prazo (data, sem hora).
     * @nullable
     */
  dueOn?: string | null;
  commentCount: number;
  attachmentCount: number;
  assignees: TaskAssigneeDto[];
}

/**
 * A coluna do quadro.
 */
export type TaskWriteRequestStatus = typeof TaskWriteRequestStatus[keyof typeof TaskWriteRequestStatus];


export const TaskWriteRequestStatus = {
  todo: 'todo',
  doing: 'doing',
  review: 'review',
  done: 'done',
} as const;

export type TaskWriteRequestPriority = typeof TaskWriteRequestPriority[keyof typeof TaskWriteRequestPriority];


export const TaskWriteRequestPriority = {
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;

/**
 * Proposto. Corpo de criação de tarefa.
 */
export interface TaskWriteRequest {
  title: string;
  /** @nullable */
  description?: string | null;
  /** A coluna do quadro. */
  status: TaskWriteRequestStatus;
  priority: TaskWriteRequestPriority;
  /**
     * Prazo (data, sem hora).
     * @nullable
     */
  dueOn?: string | null;
}

/**
 * A coluna do quadro.
 */
export type TaskPatchRequestStatus = typeof TaskPatchRequestStatus[keyof typeof TaskPatchRequestStatus];


export const TaskPatchRequestStatus = {
  todo: 'todo',
  doing: 'doing',
  review: 'review',
  done: 'done',
} as const;

export type TaskPatchRequestPriority = typeof TaskPatchRequestPriority[keyof typeof TaskPatchRequestPriority];


export const TaskPatchRequestPriority = {
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;

/**
 * Proposto. Corpo do PATCH: só o que muda. Campo ausente fica como está — ausente NÃO é o mesmo que `null`, que apaga.
 */
export interface TaskPatchRequest {
  title?: string;
  /** @nullable */
  description?: string | null;
  /** A coluna do quadro. */
  status?: TaskPatchRequestStatus;
  priority?: TaskPatchRequestPriority;
  /**
     * Prazo (data, sem hora).
     * @nullable
     */
  dueOn?: string | null;
}

/**
 * Proposto. Um item da lista A fazer.
 */
export interface TodoDto {
  id: string;
  title: string;
  done: boolean;
}

/**
 * Proposto. Marca ou desmarca.
 */
export interface TodoPatchRequest {
  done: boolean;
}

export type ProjectDtoStatus = typeof ProjectDtoStatus[keyof typeof ProjectDtoStatus];


export const ProjectDtoStatus = {
  active: 'active',
  proposed: 'proposed',
  closed: 'closed',
} as const;

/**
 * Proposto. Um projeto do Planner.
 */
export interface ProjectDto {
  id: string;
  name: string;
  status: ProjectDtoStatus;
}

/**
 * O que a barra é — dá o rótulo da pill.
 */
export type PlanItemDtoKind = typeof PlanItemDtoKind[keyof typeof PlanItemDtoKind];


export const PlanItemDtoKind = {
  task: 'task',
  order: 'order',
  delivery: 'delivery',
} as const;

/**
 * Proposto. Uma barra do gantt.
 */
export interface PlanItemDto {
  id: string;
  label: string;
  /** O que a barra é — dá o rótulo da pill. */
  kind: PlanItemDtoKind;
  startsOn: string;
  /** Previsão de término, inclusiva. */
  endsOn: string;
  /** 0 a 100. Progresso NÃO é dinheiro — a tela não o pinta de verde. */
  progressPercent: number;
}

/**
 * Proposto. Uma fase do projeto, com as barras que moram nela.
 */
export interface PlanPhaseDto {
  id: string;
  name: string;
  startsOn: string;
  endsOn: string;
  items: PlanItemDto[];
}

/**
 * Proposto. O plano inteiro de um projeto.
 */
export interface ProjectPlanDto {
  projectId: string;
  phases: PlanPhaseDto[];
}

export type ListCatalogLookupsParams = {
q?: string;
kind?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListProductsParams = {
q?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListPartnersParams = {
role?: string;
q?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListStockMovementsParams = {
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListAgendaEventsParams = {
/**
 * Início do intervalo, inclusivo (data ISO).
 */
from: string;
/**
 * Fim do intervalo, inclusivo (data ISO).
 */
to: string;
};

export type ListTasksParams = {
/**
 * Filtra uma coluna só. Ausente = o quadro inteiro.
 */
status?: ListTasksStatus;
/**
 * Busca em título e descrição.
 */
q?: string;
};

export type ListTasksStatus = typeof ListTasksStatus[keyof typeof ListTasksStatus];


export const ListTasksStatus = {
  todo: 'todo',
  doing: 'doing',
  review: 'review',
  done: 'done',
} as const;

export type ListProjectsParams = {
/**
 * Ausente = todos. O toggle do Planner manda `active,proposed` ou `closed`.
 */
status?: string;
};

