// @ts-nocheck
/* GERADO por `pnpm codegen` a partir de contracts/openapi-v1.json. NÃO EDITAR.
   `@ts-nocheck` é deliberado: ver scripts/pos-codegen.mjs. */
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Vitra ERP
 * OpenAPI spec version: v1
 */
export interface CatalogLookupDto {
  id: string;
  kind: string;
  name: string;
  active: boolean;
}

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}

export interface HealthStatus {
  status: string;
}

export interface LoginFalhou {
  detail: string;
}

export interface LoginOk {
  mustChangePassword: boolean;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface PagedResultOfCatalogLookupDto {
  rows: CatalogLookupDto[];
  total: number;
}

export interface PartnerDto {
  id: string;
  /** @nullable */
  code: string | null;
  legalName: string;
  /** @nullable */
  tradeName: string | null;
  /** @nullable */
  document: string | null;
  /** @nullable */
  email: string | null;
  isCustomer: boolean;
  isSupplier: boolean;
  isProfessional: boolean;
  /** @nullable */
  paymentTerms: string | null;
  active: boolean;
  registrationActive: boolean;
}

export interface PagedResultOfPartnerDto {
  rows: PartnerDto[];
  total: number;
}

export interface ProductDto {
  id: string;
  code: string;
  description: string;
  active: boolean;
}

export interface PagedResultOfProductDto {
  rows: ProductDto[];
  total: number;
}

export interface StockMovementDto {
  id: string;
  variantId: string;
  delta: number;
  balanceAfter: number;
  reason: string;
  occurredAt: string;
  /** @nullable */
  employeeId: string | null;
}

export interface PagedResultOfStockMovementDto {
  rows: StockMovementDto[];
  total: number;
}

export interface PartnerLinkRequest {
  /** @nullable */
  code: string | null;
  /** @nullable */
  paymentTerms: string | null;
  /** @nullable */
  active: boolean | null;
}

export interface PartnerWriteRequest {
  /** @nullable */
  document: string | null;
  /** @nullable */
  legalName: string | null;
  /** @nullable */
  tradeName: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  isCustomer: boolean | null;
  /** @nullable */
  isSupplier: boolean | null;
  /** @nullable */
  isProfessional: boolean | null;
  /** @nullable */
  code: string | null;
  /** @nullable */
  paymentTerms: string | null;
  /** @nullable */
  active: boolean | null;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
}

export interface ProductVariantDto {
  id: string;
  finish: string;
  size: string;
  active: boolean;
  /** @nullable */
  priceCents: number | null;
  /** @nullable */
  stockQty: number | null;
  /** @nullable */
  minStock: number | null;
}

export interface ProductDetailDto {
  id: string;
  code: string;
  description: string;
  active: boolean;
  variants: ProductVariantDto[];
}

export interface ProductWriteRequest {
  /** @nullable */
  code: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  active: boolean | null;
}

export interface ReadinessStatus {
  status: string;
  /** @nullable */
  detail: string | null;
  /** @nullable */
  pendingMigrations: number | null;
}

export interface SessaoAtual {
  organizationId: string;
  employeeId: string;
  /** @nullable */
  activeTenantId: string | null;
  expiresAt: string;
  mustChangePassword: boolean;
}

export interface StockMovementRequest {
  /** @nullable */
  delta: number | null;
  /** @nullable */
  reason: string | null;
}

export interface TrocarEmpresaRequest {
  tenantId: string;
}

export interface VariantWriteRequest {
  /** @nullable */
  finish: string | null;
  /** @nullable */
  size: string | null;
  /** @nullable */
  active: boolean | null;
  /** @nullable */
  priceCents: number | null;
  /** @nullable */
  minStock: number | null;
}

export interface VinculoDeEmpresa {
  tenantId: string;
  name: string;
  role: string;
}

export type ListCatalogLookupsParams = {
q?: string;
kind?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListProductsParams = {
q?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListPartnersParams = {
role?: string;
q?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListStockMovementsParams = {
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

