// @ts-nocheck
/* GERADO por `pnpm codegen` a partir de contracts/openapi-v1.json. NÃO EDITAR.
   `@ts-nocheck` é deliberado: ver scripts/pos-codegen.mjs. */
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Vitra ERP
 * OpenAPI spec version: v1
 */
export interface CatalogLookupDto {
  id: string;
  kind: string;
  name: string;
  active: boolean;
}

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}

export interface HealthStatus {
  status: string;
}

export interface LoginFalhou {
  detail: string;
}

export interface LoginOk {
  mustChangePassword: boolean;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface PagedResultOfCatalogLookupDto {
  rows: CatalogLookupDto[];
  total: number;
}

/**
 * Proposto. Dados bancários do parceiro, para pagamento de comissão ao Profissional Externo (§3, bloco `Dados Bancários`). Um objeto e não quatro campos soltos no `PartnerDto`: os quatro só fazem sentido juntos, e parceiro sem conta cadastrada manda o objeto inteiro em `null` em vez de quatro nulos que a tela teria de recombinar. O endereço do banco, que a tela também mostra, fica FORA — endereço é bloco compartilhado e o contrato ainda não tem endereço de parceiro nenhum; entrar só o do banco daria a única exceção sem a regra.
 */
export interface PartnerPayoutBankInfo {
  /**
     * Nº do banco (código FEBRABAN). Somente leitura na tela: vem da busca de banco.
     * @nullable
     */
  bankNumber: string | null;
  /**
     * Nome do banco. Somente leitura na tela, pelo mesmo motivo.
     * @nullable
     */
  bankName: string | null;
  /**
     * Nº da agência, com dígito se houver. String e não número: agência tem zero à esquerda.
     * @nullable
     */
  branchNumber: string | null;
  /**
     * Nº da conta, com dígito. String pelo mesmo motivo da agência.
     * @nullable
     */
  accountNumber: string | null;
}

export interface PartnerDto {
  id: string;
  /** @nullable */
  code: string | null;
  legalName: string;
  /** @nullable */
  tradeName: string | null;
  /** @nullable */
  document: string | null;
  /** @nullable */
  email: string | null;
  isCustomer: boolean;
  isSupplier: boolean;
  isProfessional: boolean;
  /** @nullable */
  paymentTerms: string | null;
  active: boolean;
  registrationActive: boolean;
  /**
     * Proposto. Registro Profissional — CREA, CAU ou CFT (§3). Vive no cadastro do parceiro (ORG), não no vínculo com a empresa: o conselho é do profissional, não da empresa que o contrata. Vazio em cliente e fornecedor.
     * @nullable
     */
  registration?: string | null;
  /** Proposto. Conta para pagamento de comissão. `null` quando o parceiro não tem conta cadastrada. */
  payoutBankInfo?: null | PartnerPayoutBankInfo;
}

export interface PagedResultOfPartnerDto {
  rows: PartnerDto[];
  total: number;
}

/**
 * Proposto. Medidas de uma caixa: as quatro do bloco §6.2, em string decimal pelo mesmo motivo da quantidade — 3 casas, e float perde centésimo. Sem unidade no valor: a unidade é do CAMPO (cm), não do dado; guardar "10 cm" tornaria o número inutilizável para conta e para filtro.
 */
export interface ProductDimensions {
  /**
     * `Altura`.
     * @nullable
     */
  height?: string | null;
  /**
     * `Largura`.
     * @nullable
     */
  width?: string | null;
  /**
     * `Comprimento`.
     * @nullable
     */
  length?: string | null;
  /**
     * `Raio`.
     * @nullable
     */
  radius?: string | null;
}

/**
 * Proposto. A ficha TÉCNICA do produto — a aba `Outros Dados` (§6.2) inteira. É um objeto e não 17 campos soltos no `ProductDto` porque isto é a VERTICAL: iluminação tem lúmen, ângulo e temperatura de cor; outro ramo do mesmo ERP teria outra lista, e um dia esta ficha muda sem que o cadastro de produto mude. A modelagem do banco guarda isto em `products.specs jsonb` pela mesma razão.
 *
 * O que ficou FORA, e por que: `Marca`, `Fábrica` e `Tipo de Produto` são CLASSIFICAÇÃO e viraram campo de primeiro nível — viram coluna de listagem e um dia entram na whitelist de ordenação, e nada disso funciona dentro de um jsonb. `Descrição livre` e `Publicar no site` também ficaram fora: são conteúdo e canal, não especificação.
 *
 * Todo valor é STRING: os campos da §6.2 são livres na tela do legado, e converter para número aqui inventaria precisão que o dado não tem.
 */
export interface ProductSpecs {
  /**
     * `Qtd. lâmp. por reator`.
     * @nullable
     */
  lampsPerBallast?: string | null;
  /**
     * `Consumo (Watts)`.
     * @nullable
     */
  watts?: string | null;
  /**
     * `Tensão (Volts)`.
     * @nullable
     */
  volts?: string | null;
  /**
     * `Tensão (BiVolts)`.
     * @nullable
     */
  biVolts?: string | null;
  /**
     * `Temperatura de Cor`.
     * @nullable
     */
  colorTemperature?: string | null;
  /**
     * `Ângulo`.
     * @nullable
     */
  beamAngle?: string | null;
  /**
     * `Lúmen`.
     * @nullable
     */
  lumen?: string | null;
  /**
     * `Vão livre`.
     * @nullable
     */
  clearSpan?: string | null;
  /**
     * `Corte do nicho`.
     * @nullable
     */
  nicheCut?: string | null;
  /**
     * `Peso líquido`.
     * @nullable
     */
  netWeight?: string | null;
  /**
     * `Peso bruto`.
     * @nullable
     */
  grossWeight?: string | null;
  /**
     * `Tempo de instalação`, em minutos.
     * @nullable
     */
  installationMinutes?: string | null;
  /**
     * `Garantia`, em meses.
     * @nullable
     */
  warrantyMonths?: string | null;
  /** Medidas do PRODUTO. */
  productDimensions?: null | ProductDimensions;
  /** Medidas da EMBALAGEM — são outras, e é por isso que são dois blocos. */
  packageDimensions?: null | ProductDimensions;
}

export interface ProductDto {
  id: string;
  code: string;
  description: string;
  active: boolean;
  /**
     * Proposto. `Código Especial` (§6). Um dos TRÊS códigos que o legado guarda por produto, e os três continuam porque a operação usa os três: o nosso, o especial e o reduzido. Unificar em um só quebraria busca de operador que decorou o outro.
     * @nullable
     */
  specialCode?: string | null;
  /**
     * Proposto. `Código Reduzido` (§6) — o código curto que o vendedor digita no balcão.
     * @nullable
     */
  shortCode?: string | null;
  /**
     * Proposto. `Unid. Entrada` (§6): a unidade em que o produto é COMPRADO. Nome da unidade, não id — é o mesmo texto do lookup `UNIDADE`, e o documento congela texto, não referência.
     * @nullable
     */
  unitIn?: string | null;
  /**
     * Proposto. `Qtd. Entrada` (§6). String decimal e não número: quantidade tem 3 casas e float perde centésimo — a mesma regra que o dinheiro segue em centavos.
     * @nullable
     */
  unitInQty?: string | null;
  /**
     * Proposto. `Unid. Saída` (§6): a unidade em que o produto é VENDIDO. Pode diferir da entrada — comprar em caixa e vender em peça é rotina do ramo.
     * @nullable
     */
  unitOut?: string | null;
  /**
     * Proposto. `Qtd. Saída` (§6). O par entrada×saída é que dá o fator de conversão; o front manda os quatro campos que a tela tem, e quem deriva o fator é o servidor — a modelagem do banco guarda `unit_factor`, a tela não.
     * @nullable
     */
  unitOutQty?: string | null;
  /**
     * Proposto. `Tipo de Produto` (§6) — id do `catalog-lookups` de kind `TIPO_PRODUTO`. Id E nome viajam juntos, o mesmo par de `customerId`/`customerName` do orçamento: o id é a referência que a escrita usa, o nome é o que a LISTAGEM mostra sem precisar carregar a lista de apoio inteira para resolver três colunas.
     * @nullable
     */
  productTypeId?: string | null;
  /**
     * Proposto. Nome do tipo, para exibição. Não é escrita — o `PUT` manda o id.
     * @nullable
     */
  productTypeName?: string | null;
  /**
     * Proposto. `Marca` (§6) — kind `MARCA`.
     * @nullable
     */
  brandId?: string | null;
  /**
     * Proposto. Nome da marca, para exibição.
     * @nullable
     */
  brandName?: string | null;
  /**
     * Proposto. `Fábrica` (§6) — kind `FABRICA`.
     * @nullable
     */
  factoryId?: string | null;
  /**
     * Proposto. Nome da fábrica, para exibição.
     * @nullable
     */
  factoryName?: string | null;
  /** Proposto. Ficha técnica (§6.2). `null` quando o produto não tem nenhuma medida cadastrada. */
  specs?: null | ProductSpecs;
}

export interface PagedResultOfProductDto {
  rows: ProductDto[];
  total: number;
}

export interface StockMovementDto {
  id: string;
  variantId: string;
  delta: number;
  balanceAfter: number;
  reason: string;
  occurredAt: string;
  /** @nullable */
  employeeId: string | null;
}

export interface PagedResultOfStockMovementDto {
  rows: StockMovementDto[];
  total: number;
}

export interface PartnerLinkRequest {
  /** @nullable */
  code: string | null;
  /** @nullable */
  paymentTerms: string | null;
  /** @nullable */
  active: boolean | null;
}

export interface PartnerWriteRequest {
  /** @nullable */
  document: string | null;
  /** @nullable */
  legalName: string | null;
  /** @nullable */
  tradeName: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  isCustomer: boolean | null;
  /** @nullable */
  isSupplier: boolean | null;
  /** @nullable */
  isProfessional: boolean | null;
  /** @nullable */
  code: string | null;
  /** @nullable */
  paymentTerms: string | null;
  /** @nullable */
  active: boolean | null;
  /**
     * Proposto. Registro Profissional (CREA, CAU, CFT). `PUT` substitui o registro inteiro: omitir apaga.
     * @nullable
     */
  registration?: string | null;
  /** Proposto. Conta de comissão. Vale a mesma regra do `PUT`: mandar `null` apaga a conta cadastrada. */
  payoutBankInfo?: null | PartnerPayoutBankInfo;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
}

export interface ProductVariantDto {
  id: string;
  finish: string;
  size: string;
  active: boolean;
  /** @nullable */
  priceCents: number | null;
  /** @nullable */
  stockQty: number | null;
  /** @nullable */
  minStock: number | null;
}

export interface ProductDetailDto {
  id: string;
  code: string;
  description: string;
  active: boolean;
  /**
     * Proposto. `Código Especial` (§6) — ver `ProductDto`.
     * @nullable
     */
  specialCode?: string | null;
  /**
     * Proposto. `Código Reduzido` (§6) — ver `ProductDto`.
     * @nullable
     */
  shortCode?: string | null;
  /**
     * Proposto. `Unid. Entrada` (§6) — ver `ProductDto`.
     * @nullable
     */
  unitIn?: string | null;
  /**
     * Proposto. `Qtd. Entrada` (§6), decimal em string.
     * @nullable
     */
  unitInQty?: string | null;
  /**
     * Proposto. `Unid. Saída` (§6) — ver `ProductDto`.
     * @nullable
     */
  unitOut?: string | null;
  /**
     * Proposto. `Qtd. Saída` (§6), decimal em string.
     * @nullable
     */
  unitOutQty?: string | null;
  /**
     * Proposto. `Tipo de Produto` (§6) — id do `catalog-lookups` de kind `TIPO_PRODUTO`. Id E nome viajam juntos, o mesmo par de `customerId`/`customerName` do orçamento: o id é a referência que a escrita usa, o nome é o que a LISTAGEM mostra sem precisar carregar a lista de apoio inteira para resolver três colunas.
     * @nullable
     */
  productTypeId?: string | null;
  /**
     * Proposto. Nome do tipo, para exibição. Não é escrita — o `PUT` manda o id.
     * @nullable
     */
  productTypeName?: string | null;
  /**
     * Proposto. `Marca` (§6) — kind `MARCA`.
     * @nullable
     */
  brandId?: string | null;
  /**
     * Proposto. Nome da marca, para exibição.
     * @nullable
     */
  brandName?: string | null;
  /**
     * Proposto. `Fábrica` (§6) — kind `FABRICA`.
     * @nullable
     */
  factoryId?: string | null;
  /**
     * Proposto. Nome da fábrica, para exibição.
     * @nullable
     */
  factoryName?: string | null;
  /** Proposto. Ficha técnica (§6.2). `null` quando o produto não tem nenhuma medida cadastrada. */
  specs?: null | ProductSpecs;
  variants: ProductVariantDto[];
}

export interface ProductWriteRequest {
  /** @nullable */
  code: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  active: boolean | null;
  /**
     * Proposto. `PUT` substitui o registro inteiro: omitir apaga.
     * @nullable
     */
  specialCode?: string | null;
  /**
     * Proposto. Mesma regra do `PUT`.
     * @nullable
     */
  shortCode?: string | null;
  /**
     * Proposto. Mesma regra do `PUT`.
     * @nullable
     */
  unitIn?: string | null;
  /**
     * Proposto. Decimal em string, 3 casas.
     * @nullable
     */
  unitInQty?: string | null;
  /**
     * Proposto. Mesma regra do `PUT`.
     * @nullable
     */
  unitOut?: string | null;
  /**
     * Proposto. Decimal em string, 3 casas.
     * @nullable
     */
  unitOutQty?: string | null;
  /**
     * Proposto. Só o ID viaja na escrita: o nome é do cadastro de apoio, e aceitá-lo aqui deixaria a tela renomear a lista de apoio por engano.
     * @nullable
     */
  productTypeId?: string | null;
  /**
     * Proposto. Só o id — ver `productTypeId`.
     * @nullable
     */
  brandId?: string | null;
  /**
     * Proposto. Só o id — ver `productTypeId`.
     * @nullable
     */
  factoryId?: string | null;
  /** Proposto. Ficha técnica (§6.2). `null` quando o produto não tem nenhuma medida cadastrada. */
  specs?: null | ProductSpecs;
}

export interface ReadinessStatus {
  status: string;
  /** @nullable */
  detail: string | null;
  /** @nullable */
  pendingMigrations: number | null;
}

export interface SessaoAtual {
  organizationId: string;
  employeeId: string;
  /** @nullable */
  activeTenantId: string | null;
  expiresAt: string;
  mustChangePassword: boolean;
  /**
     * Proposto. Como o operador se chama na tela — a saudação do Dashboard. `null` quando o servidor não sabe: a tela então cumprimenta sem nome, em vez de exibir e-mail ou id, que é identificador de sistema e não nome de gente.
     * @nullable
     */
  displayName?: string | null;
}

export interface StockMovementRequest {
  /** @nullable */
  delta: number | null;
  /** @nullable */
  reason: string | null;
}

export interface TrocarEmpresaRequest {
  tenantId: string;
}

export interface VariantWriteRequest {
  /** @nullable */
  finish: string | null;
  /** @nullable */
  size: string | null;
  /** @nullable */
  active: boolean | null;
  /** @nullable */
  priceCents: number | null;
  /** @nullable */
  minStock: number | null;
}

export type VinculoDeEmpresaFeaturesItem = typeof VinculoDeEmpresaFeaturesItem[keyof typeof VinculoDeEmpresaFeaturesItem];


export const VinculoDeEmpresaFeaturesItem = {
  suppliers: 'suppliers',
  professionals: 'professionals',
  employees: 'employees',
} as const;

export interface VinculoDeEmpresa {
  tenantId: string;
  name: string;
  role: string;
  /** Proposto. Recursos CONTRATADOS por esta empresa — o que ela opera, não o que o usuário pode fazer nela (isso é `role`). Conjunto fechado; valor fora dele é ignorado pelo cliente. Sempre presente: empresa sem recurso opcional devolve `[]`, nunca omite o campo — ausência viraria 'não sei' e o front teria de adivinhar entre esconder tudo e mostrar tudo. */
  features: VinculoDeEmpresaFeaturesItem[];
}

/**
 * Proposto. Os quatro números da faixa de KPI. Dinheiro em CENTAVOS, inteiro — a regra do repo vale no contrato.
 */
export interface DashboardSummaryDto {
  /** Orçamentos abertos. */
  openQuotes: number;
  /** Destes, quantos vencem nos próximos 7 dias. */
  openQuotesDueThisWeek: number;
  /** Pedidos de compra a receber. */
  incomingOrders: number;
  /** Destes, quantos com previsão para hoje. */
  incomingOrdersToday: number;
  /** Variantes com saldo abaixo do mínimo. */
  criticalStockItems: number;
  /** Vendas do mês corrente, em centavos. */
  monthSalesCents: number;
  /** Vendas do mês anterior fechado, em centavos. O front deriva a variação dos dois — percentual pronto no DTO seria número que ninguém consegue conferir na tela. */
  previousMonthSalesCents: number;
}

/**
 * Conjunto fechado — é ele que dá a cor da barra e a legenda do calendário.
 */
export type AgendaEventDtoKind = typeof AgendaEventDtoKind[keyof typeof AgendaEventDtoKind];


export const AgendaEventDtoKind = {
  delivery: 'delivery',
  quote: 'quote',
  meeting: 'meeting',
  payment: 'payment',
} as const;

/**
 * Proposto. Um compromisso da agenda.
 */
export interface AgendaEventDto {
  id: string;
  /** Início, com hora (ISO 8601). */
  startsAt: string;
  title: string;
  /**
     * A quem o compromisso se refere (cliente, obra, fornecedor).
     * @nullable
     */
  context?: string | null;
  /** Conjunto fechado — é ele que dá a cor da barra e a legenda do calendário. */
  kind: AgendaEventDtoKind;
}

/**
 * Proposto. Quem responde pela tarefa.
 */
export interface TaskAssigneeDto {
  id: string;
  name: string;
  /** As iniciais que o avatar mostra. Vêm do servidor porque quem sabe partir 'Maria da Silva' em 'MS' é quem guarda o nome — o front partindo string faria 'DS' em nome com preposição. */
  initials: string;
}

/**
 * A coluna do quadro.
 */
export type TaskDtoStatus = typeof TaskDtoStatus[keyof typeof TaskDtoStatus];


export const TaskDtoStatus = {
  todo: 'todo',
  doing: 'doing',
  review: 'review',
  done: 'done',
} as const;

export type TaskDtoPriority = typeof TaskDtoPriority[keyof typeof TaskDtoPriority];


export const TaskDtoPriority = {
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;

/**
 * Proposto. Um cartão do quadro.
 */
export interface TaskDto {
  id: string;
  title: string;
  /** @nullable */
  description?: string | null;
  /** A coluna do quadro. */
  status: TaskDtoStatus;
  priority: TaskDtoPriority;
  /**
     * Prazo (data, sem hora).
     * @nullable
     */
  dueOn?: string | null;
  commentCount: number;
  attachmentCount: number;
  assignees: TaskAssigneeDto[];
}

/**
 * A coluna do quadro.
 */
export type TaskWriteRequestStatus = typeof TaskWriteRequestStatus[keyof typeof TaskWriteRequestStatus];


export const TaskWriteRequestStatus = {
  todo: 'todo',
  doing: 'doing',
  review: 'review',
  done: 'done',
} as const;

export type TaskWriteRequestPriority = typeof TaskWriteRequestPriority[keyof typeof TaskWriteRequestPriority];


export const TaskWriteRequestPriority = {
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;

/**
 * Proposto. Corpo de criação de tarefa.
 */
export interface TaskWriteRequest {
  title: string;
  /** @nullable */
  description?: string | null;
  /** A coluna do quadro. */
  status: TaskWriteRequestStatus;
  priority: TaskWriteRequestPriority;
  /**
     * Prazo (data, sem hora).
     * @nullable
     */
  dueOn?: string | null;
}

/**
 * A coluna do quadro.
 */
export type TaskPatchRequestStatus = typeof TaskPatchRequestStatus[keyof typeof TaskPatchRequestStatus];


export const TaskPatchRequestStatus = {
  todo: 'todo',
  doing: 'doing',
  review: 'review',
  done: 'done',
} as const;

export type TaskPatchRequestPriority = typeof TaskPatchRequestPriority[keyof typeof TaskPatchRequestPriority];


export const TaskPatchRequestPriority = {
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;

/**
 * Proposto. Corpo do PATCH: só o que muda. Campo ausente fica como está — ausente NÃO é o mesmo que `null`, que apaga.
 */
export interface TaskPatchRequest {
  title?: string;
  /** @nullable */
  description?: string | null;
  /** A coluna do quadro. */
  status?: TaskPatchRequestStatus;
  priority?: TaskPatchRequestPriority;
  /**
     * Prazo (data, sem hora).
     * @nullable
     */
  dueOn?: string | null;
}

/**
 * Proposto. Um item da lista A fazer.
 */
export interface TodoDto {
  id: string;
  title: string;
  done: boolean;
}

/**
 * Proposto. Marca ou desmarca.
 */
export interface TodoPatchRequest {
  done: boolean;
}

export type ProjectDtoStatus = typeof ProjectDtoStatus[keyof typeof ProjectDtoStatus];


export const ProjectDtoStatus = {
  active: 'active',
  proposed: 'proposed',
  closed: 'closed',
} as const;

/**
 * Proposto. Um projeto do Planner.
 */
export interface ProjectDto {
  id: string;
  name: string;
  status: ProjectDtoStatus;
}

/**
 * O que a barra é — dá o rótulo da pill.
 */
export type PlanItemDtoKind = typeof PlanItemDtoKind[keyof typeof PlanItemDtoKind];


export const PlanItemDtoKind = {
  task: 'task',
  order: 'order',
  delivery: 'delivery',
} as const;

/**
 * Proposto. Uma barra do gantt.
 */
export interface PlanItemDto {
  id: string;
  label: string;
  /** O que a barra é — dá o rótulo da pill. */
  kind: PlanItemDtoKind;
  startsOn: string;
  /** Previsão de término, inclusiva. */
  endsOn: string;
  /** 0 a 100. Progresso NÃO é dinheiro — a tela não o pinta de verde. */
  progressPercent: number;
}

/**
 * Proposto. Uma fase do projeto, com as barras que moram nela.
 */
export interface PlanPhaseDto {
  id: string;
  name: string;
  startsOn: string;
  endsOn: string;
  items: PlanItemDto[];
}

/**
 * Proposto. O plano inteiro de um projeto.
 */
export interface ProjectPlanDto {
  projectId: string;
  phases: PlanPhaseDto[];
}

/**
 * Proposto. Colaborador da empresa ativa. Somente leitura neste corte: existe para resolver o `salespersonId` do orçamento e a listagem de Colaboradores. O formulário de RH (transcrição §2, ~30 campos) entra num corte próprio, com POST e PUT. Não há `code`: o legado identifica funcionário por CPF e não guarda código humano, então a coluna `Código` da listagem sai da tela em vez de exibir um uuid.
 */
export interface EmployeeDto {
  id: string;
  name: string;
  /**
     * Setor — kind `SETOR`.
     * @nullable
     */
  sector?: string | null;
  /**
     * Cargo — kind `CARGO`.
     * @nullable
     */
  jobTitle?: string | null;
  active: boolean;
}

export interface PagedResultOfEmployeeDto {
  rows: EmployeeDto[];
  total: number;
}

/**
 * Proposto. Ambiente da obra DENTRO do orçamento — o `Ambiente F5` da tela. São três camadas, e esta é a do meio: o catálogo por empresa vive em `GET /api/catalog-lookups?kind=AMBIENTE`, esta é a instância no documento, e o item aponta para ela por `environmentCode`. O `name` é CONGELADO na emissão, como o legado já faz em `VendaAmbiente.VenAmb_Descricao`: renomear o ambiente no catálogo não pode reescrever orçamento fechado, e reescrever item a item seria pior ainda. Ambiente sem item nenhum é estado legítimo — por isso é coleção própria, não um campo derivado dos itens.
 */
export interface QuoteEnvironmentDto {
  /** Id do ambiente no catálogo (`CatalogLookupDto.id`, kind `AMBIENTE`). */
  code: string;
  /** Nome congelado na emissão. */
  name: string;
  /** Ordem de exibição. O PDF do orçamento agrupa por ambiente e vai para o cliente, então a ordem é dado, não apresentação. NÃO vem do legado — `VendaAmbiente` não tem coluna de ordem. */
  order: number;
}

/**
 * Proposto. Linha da grade do orçamento. Os campos de descrição, acabamento, tamanho e preço são SNAPSHOT da emissão, não leitura do catálogo: documento comercial congela spec e preço, senão corrigir o cadastro reescreveria orçamento do ano passado.
 */
export interface QuoteItemDto {
  /** Coluna `Item`. */
  lineNumber: number;
  /**
     * Ambiente a que o item pertence. `null` = item fora de ambiente, que o legado permite (`VendaProduto.CodAmbiente` é nulável).
     * @nullable
     */
  environmentCode?: string | null;
  /**
     * Variante do catálogo (produto × acabamento × tamanho). `null` quando a linha não veio do catálogo.
     * @nullable
     */
  variantId?: string | null;
  /** Descrição congelada na emissão. */
  description: string;
  /**
     * Acabamento congelado.
     * @nullable
     */
  finish?: string | null;
  /**
     * Tamanho congelado.
     * @nullable
     */
  size?: string | null;
  /** Até 3 casas. */
  quantity: number;
  /** @nullable */
  unit?: string | null;
  /** Valor unitário congelado, em centavos. */
  unitPriceCents: number;
  /** Desconto do item. Int com 4 casas implícitas: `10000` = 1%. */
  discountPercent: number;
  /**
     * Fornecedor da linha (`PartnerDto.id`).
     * @nullable
     */
  supplierId?: string | null;
  /** @nullable */
  supplierName?: string | null;
  /**
     * Código do produto NO fornecedor — a língua em que o item é pedido.
     * @nullable
     */
  supplierCode?: string | null;
  /** @nullable */
  supplierDescription?: string | null;
  /**
     * Grupo de produto.
     * @nullable
     */
  productGroup?: string | null;
  /**
     * Tipo da peça — kind `TIPO_PECA`.
     * @nullable
     */
  pieceType?: string | null;
  /** Valor do item. Calculado pelo servidor — a escrita não manda. */
  totalCents: number;
}

/**
 * Proposto. Linha da grade na escrita. Sem `totalCents`: quem soma é o servidor.
 */
export interface QuoteItemWriteRequest {
  /** Coluna `Item`. */
  lineNumber: number;
  /**
     * Ambiente a que o item pertence. `null` = item fora de ambiente, que o legado permite (`VendaProduto.CodAmbiente` é nulável).
     * @nullable
     */
  environmentCode?: string | null;
  /**
     * Variante do catálogo (produto × acabamento × tamanho). `null` quando a linha não veio do catálogo.
     * @nullable
     */
  variantId?: string | null;
  /** Descrição congelada na emissão. */
  description: string;
  /**
     * Acabamento congelado.
     * @nullable
     */
  finish?: string | null;
  /**
     * Tamanho congelado.
     * @nullable
     */
  size?: string | null;
  /** Até 3 casas. */
  quantity: number;
  /** @nullable */
  unit?: string | null;
  /** Valor unitário congelado, em centavos. */
  unitPriceCents: number;
  /** Desconto do item. Int com 4 casas implícitas: `10000` = 1%. */
  discountPercent: number;
  /**
     * Fornecedor da linha (`PartnerDto.id`).
     * @nullable
     */
  supplierId?: string | null;
  /** @nullable */
  supplierName?: string | null;
  /**
     * Código do produto NO fornecedor — a língua em que o item é pedido.
     * @nullable
     */
  supplierCode?: string | null;
  /** @nullable */
  supplierDescription?: string | null;
  /**
     * Grupo de produto.
     * @nullable
     */
  productGroup?: string | null;
  /**
     * Tipo da peça — kind `TIPO_PECA`.
     * @nullable
     */
  pieceType?: string | null;
}

/**
 * Documento CANCELA, não desativa: `active` de cadastro não serve aqui. Espelha `Ven_Situacao` (A/C) do legado.
 */
export type QuoteDtoStatus = typeof QuoteDtoStatus[keyof typeof QuoteDtoStatus];


export const QuoteDtoStatus = {
  active: 'active',
  cancelled: 'cancelled',
} as const;

/**
 * Proposto. Orçamento na listagem — só o que a grade mostra.
 */
export interface QuoteDto {
  id: string;
  /** Número do documento. Sequência GLOBAL do grupo, atribuída pelo servidor — por isso não existe na escrita. No legado `Ven_CodigoPre` já é única entre as empresas, e cliente que escolhe número colide entre elas. */
  number: string;
  /**
     * Série do documento.
     * @nullable
     */
  series?: string | null;
  /**
     * Data de emissão.
     * @nullable
     */
  issuedAt?: string | null;
  /**
     * Data de validade — curta, ~5 dias na operação atual.
     * @nullable
     */
  expiresAt?: string | null;
  customerId: string;
  /** Nome do cliente na emissão. */
  customerName: string;
  /**
     * `Descrição da Obra` — como o operador chama a obra.
     * @nullable
     */
  projectName?: string | null;
  /** Documento CANCELA, não desativa: `active` de cadastro não serve aqui. Espelha `Ven_Situacao` (A/C) do legado. */
  status: QuoteDtoStatus;
  /** Total do orçamento, em centavos. Calculado pelo servidor. */
  totalCents: number;
}

/**
 * Documento CANCELA, não desativa: `active` de cadastro não serve aqui. Espelha `Ven_Situacao` (A/C) do legado.
 */
export type QuoteDetailDtoStatus = typeof QuoteDetailDtoStatus[keyof typeof QuoteDetailDtoStatus];


export const QuoteDetailDtoStatus = {
  active: 'active',
  cancelled: 'cancelled',
} as const;

/**
 * Desconto por produto ou geral — `Ven_TipoDesc` do legado (P/G).
 */
export type QuoteDetailDtoDiscountMode = typeof QuoteDetailDtoDiscountMode[keyof typeof QuoteDetailDtoDiscountMode];


export const QuoteDetailDtoDiscountMode = {
  product: 'product',
  general: 'general',
} as const;

/**
 * Proposto. O orçamento inteiro: cabeçalho, ambientes e itens numa resposta só. Itens e ambientes viajam embutidos porque não têm identidade fora do documento, e porque sub-recurso por linha faria um `Gravar` virar N requisições sem transação entre elas — falha no meio deixaria metade da grade gravada.
 */
export interface QuoteDetailDto {
  id: string;
  /** Número do documento. Sequência GLOBAL do grupo, atribuída pelo servidor — por isso não existe na escrita. No legado `Ven_CodigoPre` já é única entre as empresas, e cliente que escolhe número colide entre elas. */
  number: string;
  /**
     * Série do documento.
     * @nullable
     */
  series?: string | null;
  /**
     * Data de emissão.
     * @nullable
     */
  issuedAt?: string | null;
  /**
     * Data de validade — curta, ~5 dias na operação atual.
     * @nullable
     */
  expiresAt?: string | null;
  customerId: string;
  /** Nome do cliente na emissão. */
  customerName: string;
  /**
     * `Descrição da Obra` — como o operador chama a obra.
     * @nullable
     */
  projectName?: string | null;
  /** Documento CANCELA, não desativa: `active` de cadastro não serve aqui. Espelha `Ven_Situacao` (A/C) do legado. */
  status: QuoteDetailDtoStatus;
  /** Total do orçamento, em centavos. Calculado pelo servidor. */
  totalCents: number;
  /**
     * `Nº Pasta`.
     * @nullable
     */
  folderNumber?: string | null;
  /**
     * Data de fechamento.
     * @nullable
     */
  closedAt?: string | null;
  /**
     * Consultor(a) que atende — `EmployeeDto.id`.
     * @nullable
     */
  salespersonId?: string | null;
  /** @nullable */
  salespersonName?: string | null;
  /**
     * Profissional Externo (arquiteto/especificador) — é `PartnerDto.id` com papel `professional`, não cadastro à parte.
     * @nullable
     */
  professionalId?: string | null;
  /** @nullable */
  professionalName?: string | null;
  /** Desconto por produto ou geral — `Ven_TipoDesc` do legado (P/G). */
  discountMode: QuoteDetailDtoDiscountMode;
  /** Desconto geral. Int com 4 casas implícitas: `10000` = 1%. Zero quando o modo é `product`. */
  discountPercent: number;
  /** Ambientes do documento, na ordem de exibição. */
  environments: QuoteEnvironmentDto[];
  items: QuoteItemDto[];
}

/**
 * Desconto por produto ou geral — `Ven_TipoDesc` do legado (P/G).
 */
export type QuoteWriteRequestDiscountMode = typeof QuoteWriteRequestDiscountMode[keyof typeof QuoteWriteRequestDiscountMode];


export const QuoteWriteRequestDiscountMode = {
  product: 'product',
  general: 'general',
} as const;

/**
 * Proposto. Corpo de criação e de alteração. **`PUT` substitui o documento INTEIRO**, itens e ambientes junto: corpo parcial apaga o que não veio. Sem `number` (o servidor atribui), sem `status` (muda por `/cancel`), sem `totalCents` nem `customerName` (o servidor calcula e resolve).
 */
export interface QuoteWriteRequest {
  /**
     * Série do documento.
     * @nullable
     */
  series?: string | null;
  /**
     * Data de emissão.
     * @nullable
     */
  issuedAt?: string | null;
  /**
     * Data de validade — curta, ~5 dias na operação atual.
     * @nullable
     */
  expiresAt?: string | null;
  customerId: string;
  /**
     * `Descrição da Obra` — como o operador chama a obra.
     * @nullable
     */
  projectName?: string | null;
  /**
     * `Nº Pasta`.
     * @nullable
     */
  folderNumber?: string | null;
  /**
     * Data de fechamento.
     * @nullable
     */
  closedAt?: string | null;
  /**
     * Consultor(a) que atende — `EmployeeDto.id`.
     * @nullable
     */
  salespersonId?: string | null;
  /**
     * Profissional Externo (arquiteto/especificador) — é `PartnerDto.id` com papel `professional`, não cadastro à parte.
     * @nullable
     */
  professionalId?: string | null;
  /** Desconto por produto ou geral — `Ven_TipoDesc` do legado (P/G). */
  discountMode: QuoteWriteRequestDiscountMode;
  /** Desconto geral. Int com 4 casas implícitas: `10000` = 1%. Zero quando o modo é `product`. */
  discountPercent: number;
  /** Ambientes do documento, na ordem de exibição. */
  environments: QuoteEnvironmentDto[];
  items: QuoteItemWriteRequest[];
}

export interface PagedResultOfQuoteDto {
  rows: QuoteDto[];
  total: number;
}

/**
 * Proposto. Funil de venda. Vários por empresa — ver `crm_pipelines` no schema mergeado (#66).
 */
export interface CrmPipelineDto {
  id: string;
  /** Nome do funil, como o operador o chama. */
  name: string;
  /** Ordem de exibição entre os funis. */
  sort: number;
  /** Funil da oportunidade criada sem escolha explícita. Um só por empresa: marcar outro desmarca o anterior, e quem resolve isso é o servidor, na mesma transação. */
  isDefault: boolean;
  /** Desativação lógica (padrão 8 dos cadastros). Funil inativo some da escolha e não recebe oportunidade nova; as que já estão nele continuam abrindo — senão desativar viraria apagar, com outro nome. */
  active: boolean;
}

/**
 * Proposto. Corpo de criação e de alteração do funil. `PUT` substitui o registro inteiro: omitir apaga.
 */
export interface CrmPipelineWriteRequest {
  /** Nome do funil, como o operador o chama. */
  name: string;
  /** Ordem de exibição entre os funis. */
  sort: number;
  /** Funil da oportunidade criada sem escolha explícita. Um só por empresa: marcar outro desmarca o anterior, e quem resolve isso é o servidor, na mesma transação. */
  isDefault: boolean;
  /** Desativação lógica (padrão 8 dos cadastros). Funil inativo some da escolha e não recebe oportunidade nova; as que já estão nele continuam abrindo — senão desativar viraria apagar, com outro nome. */
  active: boolean;
}

export interface PagedResultOfCrmPipelineDto {
  rows: CrmPipelineDto[];
  total: number;
}

/**
 * Proposto. Estágio DE UM funil — a coluna do quadro. Não tem `active`: o schema mergeado (#66) não guarda desativação por estágio, e coluna que some com cartão dentro esconderia oportunidade sem apagá-la.
 */
export interface CrmStageDto {
  id: string;
  /** Funil a que o estágio pertence. */
  pipelineId: string;
  /** Nome do estágio — o cabeçalho da coluna no quadro. */
  name: string;
  /** Ordem da coluna no quadro. */
  sort: number;
  /** Probabilidade de fechamento. Int com 4 casas implícitas, a mesma convenção de `discountPercent`: `10000` = 1%, `1000000` = 100%. Só compara DENTRO do mesmo funil — dois funis com modelos de venda diferentes não têm escala comum. */
  probability: number;
  /** Estágio de GANHO. É propriedade do estágio e não do funil porque cada funil fecha no seu; e é dado, não rótulo, senão "Fechado" e "Ganho" viram a mesma coluna com dois nomes. */
  isWon: boolean;
  /** Estágio de PERDA. Oportunidade que entra num estágio assim exige `lostReasonId` — sem motivo, a perda não vira análise nenhuma. */
  isLost: boolean;
  /**
     * Apodrecimento: cartão parado mais dias que isto NO ESTÁGIO é sinalizado no quadro. `null` = o estágio não apodrece. Conta a partir de `stageChangedAt`, não da criação — apodrecer é "parado desde", não "velho".
     * @nullable
     */
  rotDays?: number | null;
}

/**
 * Proposto. Corpo de criação e de alteração do estágio. Sem `pipelineId`: ele vem do caminho, e dois lugares para o mesmo fato divergem.
 */
export interface CrmStageWriteRequest {
  /** Nome do estágio — o cabeçalho da coluna no quadro. */
  name: string;
  /** Ordem da coluna no quadro. */
  sort: number;
  /** Probabilidade de fechamento. Int com 4 casas implícitas, a mesma convenção de `discountPercent`: `10000` = 1%, `1000000` = 100%. Só compara DENTRO do mesmo funil — dois funis com modelos de venda diferentes não têm escala comum. */
  probability: number;
  /** Estágio de GANHO. É propriedade do estágio e não do funil porque cada funil fecha no seu; e é dado, não rótulo, senão "Fechado" e "Ganho" viram a mesma coluna com dois nomes. */
  isWon: boolean;
  /** Estágio de PERDA. Oportunidade que entra num estágio assim exige `lostReasonId` — sem motivo, a perda não vira análise nenhuma. */
  isLost: boolean;
  /**
     * Apodrecimento: cartão parado mais dias que isto NO ESTÁGIO é sinalizado no quadro. `null` = o estágio não apodrece. Conta a partir de `stageChangedAt`, não da criação — apodrecer é "parado desde", não "velho".
     * @nullable
     */
  rotDays?: number | null;
}

/**
 * Proposto. Lead e negócio no MESMO registro — converter é mudar de estágio, não cadastrar de novo. Os campos `*Name` vêm resolvidos pelo servidor: o cartão do quadro mostra três palavras e não pode carregar lista de apoio para traduzir id.
 */
export interface CrmOpportunityDto {
  id: string;
  /** Título do negócio. Existe separado do parceiro porque o cartão precisa escrever algo quando `partnerId` é nulo — e porque a mesma empresa dá origem a vários negócios. */
  name: string;
  /** Funil em que a oportunidade está. */
  pipelineId: string;
  /** Nome do funil, resolvido pelo servidor. */
  pipelineName: string;
  /** Estágio atual — sempre do MESMO funil (FK composta no banco). */
  stageId: string;
  /** Nome do estágio, resolvido pelo servidor. */
  stageName: string;
  /** Posição DENTRO do estágio, crescente. Quem atribui é o servidor — ver `PATCH /api/crm/opportunities/{id}/stage`. O cliente nunca calcula posição: índice é posição numa lista que pode estar filtrada. */
  order: number;
  /**
     * Cliente/prospect já cadastrado (`PartnerDto.id`). `null` = lead ainda sem cadastro, e aí o contato vive nos três campos `contact*`.
     * @nullable
     */
  partnerId?: string | null;
  /**
     * Nome do parceiro, resolvido pelo servidor.
     * @nullable
     */
  partnerName?: string | null;
  /**
     * Nome do contato do lead sem cadastro.
     * @nullable
     */
  contactName?: string | null;
  /**
     * E-mail do contato do lead sem cadastro.
     * @nullable
     */
  contactEmail?: string | null;
  /**
     * Telefone do contato do lead sem cadastro.
     * @nullable
     */
  contactPhone?: string | null;
  /**
     * Responsável pela oportunidade (`EmployeeDto.id`). `null` = lead que entrou por formulário e ainda não tem dono.
     * @nullable
     */
  ownerEmployeeId?: string | null;
  /**
     * Nome do responsável, resolvido pelo servidor.
     * @nullable
     */
  ownerName?: string | null;
  /**
     * Valor previsto do negócio, em centavos. `null` = ainda não estimado, que é diferente de zero.
     * @nullable
     */
  expectedValueCents?: number | null;
  /**
     * Data prevista de fechamento.
     * @nullable
     */
  expectedCloseDate?: string | null;
  /**
     * Origem do lead (indicação, feira, site).
     * @nullable
     */
  source?: string | null;
  /** Instante da última mudança de estágio. É a base do `rotDays` do estágio: sem ele o apodrecimento não calcula nada. */
  stageChangedAt: string;
  /**
     * Motivo da perda (`CrmLostReasonDto.id`). Só faz sentido em estágio `isLost`.
     * @nullable
     */
  lostReasonId?: string | null;
  /**
     * Nome do motivo de perda, resolvido pelo servidor.
     * @nullable
     */
  lostReasonName?: string | null;
  /**
     * Orçamento gerado a partir da oportunidade (`QuoteDto.id`). A oportunidade NÃO congela preço: quem congela é o orçamento.
     * @nullable
     */
  quoteId?: string | null;
  /**
     * Instante do fechamento (ganho ou perda). Escrito pelo SERVIDOR quando a oportunidade entra num estágio `isWon`/`isLost`, e limpo quando ela volta a um estágio aberto.
     * @nullable
     */
  closedAt?: string | null;
}

/**
 * Proposto. Corpo de criação e de alteração. `PUT` substitui o registro INTEIRO: campo ausente é campo apagado. Sem os `*Name` (o servidor resolve), sem `order`, sem `stageChangedAt` e sem `closedAt` — os três são consequência do movimento, e deixar o cliente escrevê-los permitiria um cartão dizer que está parado há um mês desde ontem.
 */
export interface CrmOpportunityWriteRequest {
  /** Título do negócio. Existe separado do parceiro porque o cartão precisa escrever algo quando `partnerId` é nulo — e porque a mesma empresa dá origem a vários negócios. */
  name: string;
  /**
     * Funil. Ausente ou `null` na criação = o funil `isDefault` da empresa.
     * @nullable
     */
  pipelineId?: string | null;
  /**
     * Estágio. Ausente ou `null` na criação = o primeiro estágio do funil. Trocar o estágio por aqui manda o cartão para o FIM da coluna nova e reinicia `stageChangedAt` — posicionar é o `PATCH .../stage`.
     * @nullable
     */
  stageId?: string | null;
  /**
     * Cliente/prospect já cadastrado (`PartnerDto.id`). `null` = lead ainda sem cadastro, e aí o contato vive nos três campos `contact*`.
     * @nullable
     */
  partnerId?: string | null;
  /**
     * Nome do contato do lead sem cadastro.
     * @nullable
     */
  contactName?: string | null;
  /**
     * E-mail do contato do lead sem cadastro.
     * @nullable
     */
  contactEmail?: string | null;
  /**
     * Telefone do contato do lead sem cadastro.
     * @nullable
     */
  contactPhone?: string | null;
  /**
     * Responsável pela oportunidade (`EmployeeDto.id`). `null` = lead que entrou por formulário e ainda não tem dono.
     * @nullable
     */
  ownerEmployeeId?: string | null;
  /**
     * Valor previsto do negócio, em centavos. `null` = ainda não estimado, que é diferente de zero.
     * @nullable
     */
  expectedValueCents?: number | null;
  /**
     * Data prevista de fechamento.
     * @nullable
     */
  expectedCloseDate?: string | null;
  /**
     * Origem do lead (indicação, feira, site).
     * @nullable
     */
  source?: string | null;
  /**
     * Motivo da perda (`CrmLostReasonDto.id`). Só faz sentido em estágio `isLost`.
     * @nullable
     */
  lostReasonId?: string | null;
  /**
     * Orçamento gerado a partir da oportunidade (`QuoteDto.id`). A oportunidade NÃO congela preço: quem congela é o orçamento.
     * @nullable
     */
  quoteId?: string | null;
}

/**
 * Proposto. O destino de UM movimento do quadro. Só o que muda viaja — ausente NÃO é `null`: `precedeId` ausente é "sem preferência de posição" (fim da coluna), e é por isso que ele é nulável em vez de obrigatório.
 */
export interface CrmOpportunityStagePatchRequest {
  /** Estágio de destino. De outro funil é 400 — mover de FUNIL é `PUT`, e reseta a posição. */
  stageId: string;
  /**
     * Id do cartão na frente do qual a oportunidade fica; `null` = fim da coluna. É referência a VIZINHO, não índice: índice é posição numa lista que pode estar filtrada, vizinho é um fato sobre dois registros que o servidor confere. Cartão que não está no estágio de destino é 400.
     * @nullable
     */
  precedeId?: string | null;
  /**
     * Motivo da perda. **Obrigatório quando o estágio de destino tem `isLost`** — sem ele a resposta é 400, porque perda sem motivo não vira análise. Ignorado nos demais estágios.
     * @nullable
     */
  lostReasonId?: string | null;
}

export interface PagedResultOfCrmOpportunityDto {
  rows: CrmOpportunityDto[];
  total: number;
}

/**
 * Proposto. Motivo de perda catalogado — vira análise, não texto livre.
 */
export interface CrmLostReasonDto {
  id: string;
  /** Motivo da perda, como entra no relatório. */
  name: string;
  /** Desativação lógica: motivo aposentado some da escolha, mas continua legível nas oportunidades antigas. */
  active: boolean;
}

/**
 * Proposto. Corpo de criação e de alteração do motivo de perda.
 */
export interface CrmLostReasonWriteRequest {
  /** Motivo da perda, como entra no relatório. */
  name: string;
  /** Desativação lógica: motivo aposentado some da escolha, mas continua legível nas oportunidades antigas. */
  active: boolean;
}

export interface PagedResultOfCrmLostReasonDto {
  rows: CrmLostReasonDto[];
  total: number;
}

export type ListCatalogLookupsParams = {
q?: string;
kind?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListProductsParams = {
q?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListPartnersParams = {
role?: string;
q?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListStockMovementsParams = {
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListAgendaEventsParams = {
/**
 * Início do intervalo, inclusivo (data ISO).
 */
from: string;
/**
 * Fim do intervalo, inclusivo (data ISO).
 */
to: string;
};

export type ListTasksParams = {
/**
 * Filtra uma coluna só. Ausente = o quadro inteiro.
 */
status?: ListTasksStatus;
/**
 * Busca em título e descrição.
 */
q?: string;
};

export type ListTasksStatus = typeof ListTasksStatus[keyof typeof ListTasksStatus];


export const ListTasksStatus = {
  todo: 'todo',
  doing: 'doing',
  review: 'review',
  done: 'done',
} as const;

export type ListProjectsParams = {
/**
 * Ausente = todos. O toggle do Planner manda `active,proposed` ou `closed`.
 */
status?: string;
};

export type ListEmployeesParams = {
q?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListQuotesParams = {
q?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListCrmPipelinesParams = {
q?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListCrmOpportunitiesParams = {
/**
 * Só as oportunidades deste funil.
 */
pipelineId?: string;
/**
 * Só as deste estágio — uma coluna do quadro.
 */
stageId?: string;
/**
 * Só as deste responsável.
 */
ownerEmployeeId?: string;
/**
 * `true` = só as ABERTAS (estágio sem `isWon` nem `isLost`). Ausente = todas. É filtro por PROPRIEDADE do estágio, não por lista de ids: a tela não pode montar a lista de estágios ganhos de cada funil para depois pedir o resto.
 */
open?: boolean;
q?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

export type ListCrmLostReasonsParams = {
q?: string;
sortBy?: string;
sortDesc?: boolean;
page?: number;
pageSize?: number;
};

