// @ts-nocheck
/* GERADO por `pnpm codegen` a partir de contracts/openapi-v1.json. NÃO EDITAR.
   `@ts-nocheck` é deliberado: ver scripts/pos-codegen.mjs. */
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Vitra ERP
 * OpenAPI spec version: v1
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  getAuthLoginResponseMock,
  getAuthMeResponseMock,
  getAuthTenantsResponseMock,
  getCreatePartnerResponseMock,
  getCreateProductResponseMock,
  getCreateStockMovementResponseMock,
  getCreateVariantResponseMock,
  getGetPartnerResponseMock,
  getGetProductResponseMock,
  getHealthDbResponseMock,
  getHealthResponseMock,
  getLinkPartnerResponseMock,
  getListCatalogLookupsResponseMock,
  getListPartnersResponseMock,
  getListProductsResponseMock,
  getListStockMovementsResponseMock,
  getUpdatePartnerResponseMock,
  getUpdateProductResponseMock,
  getUpdateVariantResponseMock
} from './index.faker';

import type {
  HealthStatus,
  LoginOk,
  PagedResultOfCatalogLookupDto,
  PagedResultOfPartnerDto,
  PagedResultOfProductDto,
  PagedResultOfStockMovementDto,
  PartnerDto,
  ProductDetailDto,
  ProductDto,
  ProductVariantDto,
  ReadinessStatus,
  SessaoAtual,
  StockMovementDto,
  VinculoDeEmpresa
} from './index.schemas';

export { getHealthResponseMock, getHealthDbResponseMock, getListCatalogLookupsResponseMock, getListProductsResponseMock, getCreateProductResponseMock, getGetProductResponseMock, getUpdateProductResponseMock, getCreateVariantResponseMock, getUpdateVariantResponseMock, getListPartnersResponseMock, getCreatePartnerResponseMock, getGetPartnerResponseMock, getUpdatePartnerResponseMock, getLinkPartnerResponseMock, getCreateStockMovementResponseMock, getListStockMovementsResponseMock, getAuthLoginResponseMock, getAuthMeResponseMock, getAuthTenantsResponseMock } from './index.faker';


export const getHealthMockHandler = (overrideResponse?: HealthStatus | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HealthStatus> | HealthStatus), options?: RequestHandlerOptions) => {
  return http.get('*/health', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getHealthResponseMock(),
      { status: 200
      })
  }, options)
}

export const getHealthDbMockHandler = (overrideResponse?: ReadinessStatus | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ReadinessStatus> | ReadinessStatus), options?: RequestHandlerOptions) => {
  return http.get('*/health/db', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getHealthDbResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListCatalogLookupsMockHandler = (overrideResponse?: PagedResultOfCatalogLookupDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PagedResultOfCatalogLookupDto> | PagedResultOfCatalogLookupDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/catalog-lookups', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListCatalogLookupsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListProductsMockHandler = (overrideResponse?: PagedResultOfProductDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PagedResultOfProductDto> | PagedResultOfProductDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/products', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListProductsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateProductMockHandler = (overrideResponse?: ProductDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ProductDto> | ProductDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/products', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateProductResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetProductMockHandler = (overrideResponse?: ProductDetailDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProductDetailDto> | ProductDetailDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/products/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProductResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateProductMockHandler = (overrideResponse?: ProductDto | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<ProductDto> | ProductDto), options?: RequestHandlerOptions) => {
  return http.put('*/api/products/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateProductResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateVariantMockHandler = (overrideResponse?: ProductVariantDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ProductVariantDto> | ProductVariantDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/products/:productId/variants', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateVariantResponseMock(),
      { status: 201
      })
  }, options)
}

export const getUpdateVariantMockHandler = (overrideResponse?: ProductVariantDto | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<ProductVariantDto> | ProductVariantDto), options?: RequestHandlerOptions) => {
  return http.put('*/api/products/:productId/variants/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateVariantResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListPartnersMockHandler = (overrideResponse?: PagedResultOfPartnerDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PagedResultOfPartnerDto> | PagedResultOfPartnerDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/partners', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListPartnersResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreatePartnerMockHandler = (overrideResponse?: PartnerDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PartnerDto> | PartnerDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/partners', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreatePartnerResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetPartnerMockHandler = (overrideResponse?: PartnerDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PartnerDto> | PartnerDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/partners/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetPartnerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdatePartnerMockHandler = (overrideResponse?: PartnerDto | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<PartnerDto> | PartnerDto), options?: RequestHandlerOptions) => {
  return http.put('*/api/partners/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdatePartnerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getLinkPartnerMockHandler = (overrideResponse?: PartnerDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PartnerDto> | PartnerDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/partners/:id/link', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLinkPartnerResponseMock(),
      { status: 201
      })
  }, options)
}

export const getCreateStockMovementMockHandler = (overrideResponse?: StockMovementDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<StockMovementDto> | StockMovementDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/variants/:variantId/stock-movements', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateStockMovementResponseMock(),
      { status: 201
      })
  }, options)
}

export const getListStockMovementsMockHandler = (overrideResponse?: PagedResultOfStockMovementDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PagedResultOfStockMovementDto> | PagedResultOfStockMovementDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/variants/:variantId/stock-movements', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListStockMovementsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getAuthLoginMockHandler = (overrideResponse?: LoginOk | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<LoginOk> | LoginOk), options?: RequestHandlerOptions) => {
  return http.post('*/auth/login', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAuthLoginResponseMock(),
      { status: 200
      })
  }, options)
}

export const getAuthLogoutMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/auth/logout', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getAuthChangePasswordMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/auth/change-password', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getAuthMeMockHandler = (overrideResponse?: SessaoAtual | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SessaoAtual> | SessaoAtual), options?: RequestHandlerOptions) => {
  return http.get('*/auth/me', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAuthMeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getAuthTenantsMockHandler = (overrideResponse?: VinculoDeEmpresa[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<VinculoDeEmpresa[]> | VinculoDeEmpresa[]), options?: RequestHandlerOptions) => {
  return http.get('*/auth/tenants', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAuthTenantsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getAuthSetActiveTenantMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/auth/active-tenant', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getVitraERPMock = () => [
  getHealthMockHandler(),
  getHealthDbMockHandler(),
  getListCatalogLookupsMockHandler(),
  getListProductsMockHandler(),
  getCreateProductMockHandler(),
  getGetProductMockHandler(),
  getUpdateProductMockHandler(),
  getCreateVariantMockHandler(),
  getUpdateVariantMockHandler(),
  getListPartnersMockHandler(),
  getCreatePartnerMockHandler(),
  getGetPartnerMockHandler(),
  getUpdatePartnerMockHandler(),
  getLinkPartnerMockHandler(),
  getCreateStockMovementMockHandler(),
  getListStockMovementsMockHandler(),
  getAuthLoginMockHandler(),
  getAuthLogoutMockHandler(),
  getAuthChangePasswordMockHandler(),
  getAuthMeMockHandler(),
  getAuthTenantsMockHandler(),
  getAuthSetActiveTenantMockHandler()
]
