// @ts-nocheck
/* GERADO por `pnpm codegen` a partir de contracts/openapi-v1.json. NÃO EDITAR.
   `@ts-nocheck` é deliberado: ver scripts/pos-codegen.mjs. */
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Vitra ERP
 * OpenAPI spec version: v1
 */
import type {
  AgendaEventDto,
  ChangePasswordRequest,
  DashboardSummaryDto,
  HealthStatus,
  ListAgendaEventsParams,
  ListCatalogLookupsParams,
  ListEmployeesParams,
  ListPartnersParams,
  ListProductsParams,
  ListProjectsParams,
  ListQuotesParams,
  ListStockMovementsParams,
  ListTasksParams,
  LoginFalhou,
  LoginOk,
  LoginRequest,
  PagedResultOfCatalogLookupDto,
  PagedResultOfEmployeeDto,
  PagedResultOfPartnerDto,
  PagedResultOfProductDto,
  PagedResultOfQuoteDto,
  PagedResultOfStockMovementDto,
  PartnerDto,
  PartnerLinkRequest,
  PartnerWriteRequest,
  ProblemDetails,
  ProductDetailDto,
  ProductDto,
  ProductVariantDto,
  ProductWriteRequest,
  ProjectDto,
  ProjectPlanDto,
  QuoteDetailDto,
  QuoteWriteRequest,
  ReadinessStatus,
  SessaoAtual,
  StockMovementDto,
  StockMovementRequest,
  TaskDto,
  TaskPatchRequest,
  TaskWriteRequest,
  TodoDto,
  TodoPatchRequest,
  TrocarEmpresaRequest,
  VariantWriteRequest,
  VinculoDeEmpresa
} from './index.schemas';

import { apiFetch } from '../http';

export type healthResponse200 = {
  data: HealthStatus
  status: 200
}

export type healthResponseSuccess = (healthResponse200) & {
  headers: Headers;
};
;

export type healthResponse = (healthResponseSuccess)

export const getHealthUrl = () => {




  return `/health`
}

export const health = async ( options?: Parameters<typeof apiFetch>[1]): Promise<healthResponse> => {

  return apiFetch<healthResponse>(getHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type healthDbResponse200 = {
  data: ReadinessStatus
  status: 200
}

export type healthDbResponse503 = {
  data: ReadinessStatus
  status: 503
}

export type healthDbResponseSuccess = (healthDbResponse200) & {
  headers: Headers;
};
export type healthDbResponseError = (healthDbResponse503) & {
  headers: Headers;
};

export type healthDbResponse = (healthDbResponseSuccess | healthDbResponseError)

export const getHealthDbUrl = () => {




  return `/health/db`
}

export const healthDb = async ( options?: Parameters<typeof apiFetch>[1]): Promise<healthDbResponse> => {

  return apiFetch<healthDbResponse>(getHealthDbUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type listCatalogLookupsResponse200 = {
  data: PagedResultOfCatalogLookupDto
  status: 200
}

export type listCatalogLookupsResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listCatalogLookupsResponseSuccess = (listCatalogLookupsResponse200) & {
  headers: Headers;
};
export type listCatalogLookupsResponseError = (listCatalogLookupsResponse400) & {
  headers: Headers;
};

export type listCatalogLookupsResponse = (listCatalogLookupsResponseSuccess | listCatalogLookupsResponseError)

export const getListCatalogLookupsUrl = (params?: ListCatalogLookupsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/catalog-lookups?${stringifiedParams}` : `/api/catalog-lookups`
}

export const listCatalogLookups = async (params?: ListCatalogLookupsParams, options?: Parameters<typeof apiFetch>[1]): Promise<listCatalogLookupsResponse> => {

  return apiFetch<listCatalogLookupsResponse>(getListCatalogLookupsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type listProductsResponse200 = {
  data: PagedResultOfProductDto
  status: 200
}

export type listProductsResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listProductsResponse409 = {
  data: ProblemDetails
  status: 409
}

export type listProductsResponseSuccess = (listProductsResponse200) & {
  headers: Headers;
};
export type listProductsResponseError = (listProductsResponse400 | listProductsResponse409) & {
  headers: Headers;
};

export type listProductsResponse = (listProductsResponseSuccess | listProductsResponseError)

export const getListProductsUrl = (params?: ListProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/products?${stringifiedParams}` : `/api/products`
}

export const listProducts = async (params?: ListProductsParams, options?: Parameters<typeof apiFetch>[1]): Promise<listProductsResponse> => {

  return apiFetch<listProductsResponse>(getListProductsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type createProductResponse201 = {
  data: ProductDto
  status: 201
}

export type createProductResponse400 = {
  data: ProblemDetails
  status: 400
}

export type createProductResponse403 = {
  data: ProblemDetails
  status: 403
}

export type createProductResponse409 = {
  data: ProblemDetails
  status: 409
}

export type createProductResponseSuccess = (createProductResponse201) & {
  headers: Headers;
};
export type createProductResponseError = (createProductResponse400 | createProductResponse403 | createProductResponse409) & {
  headers: Headers;
};

export type createProductResponse = (createProductResponseSuccess | createProductResponseError)

export const getCreateProductUrl = () => {




  return `/api/products`
}

export const createProduct = async (productWriteRequest: ProductWriteRequest, options?: Parameters<typeof apiFetch>[1]): Promise<createProductResponse> => {

  return apiFetch<createProductResponse>(getCreateProductUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(productWriteRequest)
  }
);}



export type getProductResponse200 = {
  data: ProductDetailDto
  status: 200
}

export type getProductResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getProductResponse409 = {
  data: ProblemDetails
  status: 409
}

export type getProductResponseSuccess = (getProductResponse200) & {
  headers: Headers;
};
export type getProductResponseError = (getProductResponse404 | getProductResponse409) & {
  headers: Headers;
};

export type getProductResponse = (getProductResponseSuccess | getProductResponseError)

export const getGetProductUrl = (id: string,) => {




  return `/api/products/${id}`
}

export const getProduct = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<getProductResponse> => {

  return apiFetch<getProductResponse>(getGetProductUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type updateProductResponse200 = {
  data: ProductDto
  status: 200
}

export type updateProductResponse400 = {
  data: ProblemDetails
  status: 400
}

export type updateProductResponse403 = {
  data: ProblemDetails
  status: 403
}

export type updateProductResponse404 = {
  data: ProblemDetails
  status: 404
}

export type updateProductResponse409 = {
  data: ProblemDetails
  status: 409
}

export type updateProductResponseSuccess = (updateProductResponse200) & {
  headers: Headers;
};
export type updateProductResponseError = (updateProductResponse400 | updateProductResponse403 | updateProductResponse404 | updateProductResponse409) & {
  headers: Headers;
};

export type updateProductResponse = (updateProductResponseSuccess | updateProductResponseError)

export const getUpdateProductUrl = (id: string,) => {




  return `/api/products/${id}`
}

export const updateProduct = async (id: string,
    productWriteRequest: ProductWriteRequest, options?: Parameters<typeof apiFetch>[1]): Promise<updateProductResponse> => {

  return apiFetch<updateProductResponse>(getUpdateProductUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(productWriteRequest)
  }
);}



export type createVariantResponse201 = {
  data: ProductVariantDto
  status: 201
}

export type createVariantResponse400 = {
  data: ProblemDetails
  status: 400
}

export type createVariantResponse403 = {
  data: ProblemDetails
  status: 403
}

export type createVariantResponse404 = {
  data: ProblemDetails
  status: 404
}

export type createVariantResponse409 = {
  data: ProblemDetails
  status: 409
}

export type createVariantResponseSuccess = (createVariantResponse201) & {
  headers: Headers;
};
export type createVariantResponseError = (createVariantResponse400 | createVariantResponse403 | createVariantResponse404 | createVariantResponse409) & {
  headers: Headers;
};

export type createVariantResponse = (createVariantResponseSuccess | createVariantResponseError)

export const getCreateVariantUrl = (productId: string,) => {




  return `/api/products/${productId}/variants`
}

export const createVariant = async (productId: string,
    variantWriteRequest: VariantWriteRequest, options?: Parameters<typeof apiFetch>[1]): Promise<createVariantResponse> => {

  return apiFetch<createVariantResponse>(getCreateVariantUrl(productId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(variantWriteRequest)
  }
);}



export type updateVariantResponse200 = {
  data: ProductVariantDto
  status: 200
}

export type updateVariantResponse400 = {
  data: ProblemDetails
  status: 400
}

export type updateVariantResponse403 = {
  data: ProblemDetails
  status: 403
}

export type updateVariantResponse404 = {
  data: ProblemDetails
  status: 404
}

export type updateVariantResponse409 = {
  data: ProblemDetails
  status: 409
}

export type updateVariantResponseSuccess = (updateVariantResponse200) & {
  headers: Headers;
};
export type updateVariantResponseError = (updateVariantResponse400 | updateVariantResponse403 | updateVariantResponse404 | updateVariantResponse409) & {
  headers: Headers;
};

export type updateVariantResponse = (updateVariantResponseSuccess | updateVariantResponseError)

export const getUpdateVariantUrl = (productId: string,
    id: string,) => {




  return `/api/products/${productId}/variants/${id}`
}

export const updateVariant = async (productId: string,
    id: string,
    variantWriteRequest: VariantWriteRequest, options?: Parameters<typeof apiFetch>[1]): Promise<updateVariantResponse> => {

  return apiFetch<updateVariantResponse>(getUpdateVariantUrl(productId,id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(variantWriteRequest)
  }
);}



export type listPartnersResponse200 = {
  data: PagedResultOfPartnerDto
  status: 200
}

export type listPartnersResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listPartnersResponse409 = {
  data: ProblemDetails
  status: 409
}

export type listPartnersResponseSuccess = (listPartnersResponse200) & {
  headers: Headers;
};
export type listPartnersResponseError = (listPartnersResponse400 | listPartnersResponse409) & {
  headers: Headers;
};

export type listPartnersResponse = (listPartnersResponseSuccess | listPartnersResponseError)

export const getListPartnersUrl = (params?: ListPartnersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/partners?${stringifiedParams}` : `/api/partners`
}

export const listPartners = async (params?: ListPartnersParams, options?: Parameters<typeof apiFetch>[1]): Promise<listPartnersResponse> => {

  return apiFetch<listPartnersResponse>(getListPartnersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type createPartnerResponse201 = {
  data: PartnerDto
  status: 201
}

export type createPartnerResponse400 = {
  data: ProblemDetails
  status: 400
}

export type createPartnerResponse403 = {
  data: ProblemDetails
  status: 403
}

export type createPartnerResponse409 = {
  data: ProblemDetails
  status: 409
}

export type createPartnerResponseSuccess = (createPartnerResponse201) & {
  headers: Headers;
};
export type createPartnerResponseError = (createPartnerResponse400 | createPartnerResponse403 | createPartnerResponse409) & {
  headers: Headers;
};

export type createPartnerResponse = (createPartnerResponseSuccess | createPartnerResponseError)

export const getCreatePartnerUrl = () => {




  return `/api/partners`
}

export const createPartner = async (partnerWriteRequest: PartnerWriteRequest, options?: Parameters<typeof apiFetch>[1]): Promise<createPartnerResponse> => {

  return apiFetch<createPartnerResponse>(getCreatePartnerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(partnerWriteRequest)
  }
);}



export type getPartnerResponse200 = {
  data: PartnerDto
  status: 200
}

export type getPartnerResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getPartnerResponse409 = {
  data: ProblemDetails
  status: 409
}

export type getPartnerResponseSuccess = (getPartnerResponse200) & {
  headers: Headers;
};
export type getPartnerResponseError = (getPartnerResponse404 | getPartnerResponse409) & {
  headers: Headers;
};

export type getPartnerResponse = (getPartnerResponseSuccess | getPartnerResponseError)

export const getGetPartnerUrl = (id: string,) => {




  return `/api/partners/${id}`
}

export const getPartner = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<getPartnerResponse> => {

  return apiFetch<getPartnerResponse>(getGetPartnerUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type updatePartnerResponse200 = {
  data: PartnerDto
  status: 200
}

export type updatePartnerResponse400 = {
  data: ProblemDetails
  status: 400
}

export type updatePartnerResponse403 = {
  data: ProblemDetails
  status: 403
}

export type updatePartnerResponse404 = {
  data: ProblemDetails
  status: 404
}

export type updatePartnerResponse409 = {
  data: ProblemDetails
  status: 409
}

export type updatePartnerResponseSuccess = (updatePartnerResponse200) & {
  headers: Headers;
};
export type updatePartnerResponseError = (updatePartnerResponse400 | updatePartnerResponse403 | updatePartnerResponse404 | updatePartnerResponse409) & {
  headers: Headers;
};

export type updatePartnerResponse = (updatePartnerResponseSuccess | updatePartnerResponseError)

export const getUpdatePartnerUrl = (id: string,) => {




  return `/api/partners/${id}`
}

export const updatePartner = async (id: string,
    partnerWriteRequest: PartnerWriteRequest, options?: Parameters<typeof apiFetch>[1]): Promise<updatePartnerResponse> => {

  return apiFetch<updatePartnerResponse>(getUpdatePartnerUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(partnerWriteRequest)
  }
);}



export type linkPartnerResponse201 = {
  data: PartnerDto
  status: 201
}

export type linkPartnerResponse403 = {
  data: ProblemDetails
  status: 403
}

export type linkPartnerResponse404 = {
  data: ProblemDetails
  status: 404
}

export type linkPartnerResponse409 = {
  data: ProblemDetails
  status: 409
}

export type linkPartnerResponseSuccess = (linkPartnerResponse201) & {
  headers: Headers;
};
export type linkPartnerResponseError = (linkPartnerResponse403 | linkPartnerResponse404 | linkPartnerResponse409) & {
  headers: Headers;
};

export type linkPartnerResponse = (linkPartnerResponseSuccess | linkPartnerResponseError)

export const getLinkPartnerUrl = (id: string,) => {




  return `/api/partners/${id}/link`
}

export const linkPartner = async (id: string,
    nullPartnerLinkRequest?: null | PartnerLinkRequest, options?: Parameters<typeof apiFetch>[1]): Promise<linkPartnerResponse> => {

  return apiFetch<linkPartnerResponse>(getLinkPartnerUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(nullPartnerLinkRequest)
  }
);}



export type createStockMovementResponse201 = {
  data: StockMovementDto
  status: 201
}

export type createStockMovementResponse400 = {
  data: ProblemDetails
  status: 400
}

export type createStockMovementResponse403 = {
  data: ProblemDetails
  status: 403
}

export type createStockMovementResponse404 = {
  data: ProblemDetails
  status: 404
}

export type createStockMovementResponse409 = {
  data: ProblemDetails
  status: 409
}

export type createStockMovementResponseSuccess = (createStockMovementResponse201) & {
  headers: Headers;
};
export type createStockMovementResponseError = (createStockMovementResponse400 | createStockMovementResponse403 | createStockMovementResponse404 | createStockMovementResponse409) & {
  headers: Headers;
};

export type createStockMovementResponse = (createStockMovementResponseSuccess | createStockMovementResponseError)

export const getCreateStockMovementUrl = (variantId: string,) => {




  return `/api/variants/${variantId}/stock-movements`
}

export const createStockMovement = async (variantId: string,
    stockMovementRequest: StockMovementRequest, options?: Parameters<typeof apiFetch>[1]): Promise<createStockMovementResponse> => {

  return apiFetch<createStockMovementResponse>(getCreateStockMovementUrl(variantId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(stockMovementRequest)
  }
);}



export type listStockMovementsResponse200 = {
  data: PagedResultOfStockMovementDto
  status: 200
}

export type listStockMovementsResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listStockMovementsResponse409 = {
  data: ProblemDetails
  status: 409
}

export type listStockMovementsResponseSuccess = (listStockMovementsResponse200) & {
  headers: Headers;
};
export type listStockMovementsResponseError = (listStockMovementsResponse400 | listStockMovementsResponse409) & {
  headers: Headers;
};

export type listStockMovementsResponse = (listStockMovementsResponseSuccess | listStockMovementsResponseError)

export const getListStockMovementsUrl = (variantId: string,
    params?: ListStockMovementsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/variants/${variantId}/stock-movements?${stringifiedParams}` : `/api/variants/${variantId}/stock-movements`
}

export const listStockMovements = async (variantId: string,
    params?: ListStockMovementsParams, options?: Parameters<typeof apiFetch>[1]): Promise<listStockMovementsResponse> => {

  return apiFetch<listStockMovementsResponse>(getListStockMovementsUrl(variantId,params),
  {
    ...options,
    method: 'GET'


  }
);}



export type authLoginResponse200 = {
  data: LoginOk
  status: 200
}

export type authLoginResponse401 = {
  data: LoginFalhou
  status: 401
}

export type authLoginResponseSuccess = (authLoginResponse200) & {
  headers: Headers;
};
export type authLoginResponseError = (authLoginResponse401) & {
  headers: Headers;
};

export type authLoginResponse = (authLoginResponseSuccess | authLoginResponseError)

export const getAuthLoginUrl = () => {




  return `/auth/login`
}

export const authLogin = async (loginRequest: LoginRequest, options?: Parameters<typeof apiFetch>[1]): Promise<authLoginResponse> => {

  return apiFetch<authLoginResponse>(getAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest)
  }
);}



export type authLogoutResponse204 = {
  data: void
  status: 204
}

export type authLogoutResponseSuccess = (authLogoutResponse204) & {
  headers: Headers;
};
;

export type authLogoutResponse = (authLogoutResponseSuccess)

export const getAuthLogoutUrl = () => {




  return `/auth/logout`
}

export const authLogout = async ( options?: Parameters<typeof apiFetch>[1]): Promise<authLogoutResponse> => {

  return apiFetch<authLogoutResponse>(getAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export type authChangePasswordResponse204 = {
  data: void
  status: 204
}

export type authChangePasswordResponse400 = {
  data: LoginFalhou
  status: 400
}

export type authChangePasswordResponseSuccess = (authChangePasswordResponse204) & {
  headers: Headers;
};
export type authChangePasswordResponseError = (authChangePasswordResponse400) & {
  headers: Headers;
};

export type authChangePasswordResponse = (authChangePasswordResponseSuccess | authChangePasswordResponseError)

export const getAuthChangePasswordUrl = () => {




  return `/auth/change-password`
}

export const authChangePassword = async (changePasswordRequest: ChangePasswordRequest, options?: Parameters<typeof apiFetch>[1]): Promise<authChangePasswordResponse> => {

  return apiFetch<authChangePasswordResponse>(getAuthChangePasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(changePasswordRequest)
  }
);}



export type authMeResponse200 = {
  data: SessaoAtual
  status: 200
}

export type authMeResponseSuccess = (authMeResponse200) & {
  headers: Headers;
};
;

export type authMeResponse = (authMeResponseSuccess)

export const getAuthMeUrl = () => {




  return `/auth/me`
}

export const authMe = async ( options?: Parameters<typeof apiFetch>[1]): Promise<authMeResponse> => {

  return apiFetch<authMeResponse>(getAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type authTenantsResponse200 = {
  data: VinculoDeEmpresa[]
  status: 200
}

export type authTenantsResponseSuccess = (authTenantsResponse200) & {
  headers: Headers;
};
;

export type authTenantsResponse = (authTenantsResponseSuccess)

export const getAuthTenantsUrl = () => {




  return `/auth/tenants`
}

export const authTenants = async ( options?: Parameters<typeof apiFetch>[1]): Promise<authTenantsResponse> => {

  return apiFetch<authTenantsResponse>(getAuthTenantsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type authSetActiveTenantResponse204 = {
  data: void
  status: 204
}

export type authSetActiveTenantResponse400 = {
  data: LoginFalhou
  status: 400
}

export type authSetActiveTenantResponseSuccess = (authSetActiveTenantResponse204) & {
  headers: Headers;
};
export type authSetActiveTenantResponseError = (authSetActiveTenantResponse400) & {
  headers: Headers;
};

export type authSetActiveTenantResponse = (authSetActiveTenantResponseSuccess | authSetActiveTenantResponseError)

export const getAuthSetActiveTenantUrl = () => {




  return `/auth/active-tenant`
}

export const authSetActiveTenant = async (trocarEmpresaRequest: TrocarEmpresaRequest, options?: Parameters<typeof apiFetch>[1]): Promise<authSetActiveTenantResponse> => {

  return apiFetch<authSetActiveTenantResponse>(getAuthSetActiveTenantUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(trocarEmpresaRequest)
  }
);}



export type getDashboardSummaryResponse200 = {
  data: DashboardSummaryDto
  status: 200
}

export type getDashboardSummaryResponse409 = {
  data: ProblemDetails
  status: 409
}

export type getDashboardSummaryResponseSuccess = (getDashboardSummaryResponse200) & {
  headers: Headers;
};
export type getDashboardSummaryResponseError = (getDashboardSummaryResponse409) & {
  headers: Headers;
};

export type getDashboardSummaryResponse = (getDashboardSummaryResponseSuccess | getDashboardSummaryResponseError)

export const getGetDashboardSummaryUrl = () => {




  return `/api/dashboard/summary`
}

/**
 * Proposto. Os quatro indicadores da faixa de KPI do Dashboard, da EMPRESA ATIVA da sessão. Números derivados do movimento — o servidor apura, o front só formata. Sessão sem empresa ativa responde tudo em zero, pela mesma regra das listagens (lista vazia, não erro).
 */
export const getDashboardSummary = async ( options?: Parameters<typeof apiFetch>[1]): Promise<getDashboardSummaryResponse> => {

  return apiFetch<getDashboardSummaryResponse>(getGetDashboardSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type listAgendaEventsResponse200 = {
  data: AgendaEventDto[]
  status: 200
}

export type listAgendaEventsResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listAgendaEventsResponseSuccess = (listAgendaEventsResponse200) & {
  headers: Headers;
};
export type listAgendaEventsResponseError = (listAgendaEventsResponse400) & {
  headers: Headers;
};

export type listAgendaEventsResponse = (listAgendaEventsResponseSuccess | listAgendaEventsResponseError)

export const getListAgendaEventsUrl = (params: ListAgendaEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/dashboard/agenda?${stringifiedParams}` : `/api/dashboard/agenda`
}

/**
 * Proposto. Compromissos com data dentro do intervalo [from, to], da empresa ativa. UMA consulta serve o mini-calendário (o mês inteiro, para marcar os dias) e a Agenda de hoje (o recorte do dia) — dois caminhos devolveriam a mesma coisa em granularidades diferentes e sairiam do ar em desacordo.
 */
export const listAgendaEvents = async (params: ListAgendaEventsParams, options?: Parameters<typeof apiFetch>[1]): Promise<listAgendaEventsResponse> => {

  return apiFetch<listAgendaEventsResponse>(getListAgendaEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type listTasksResponse200 = {
  data: TaskDto[]
  status: 200
}

export type listTasksResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listTasksResponseSuccess = (listTasksResponse200) & {
  headers: Headers;
};
export type listTasksResponseError = (listTasksResponse400) & {
  headers: Headers;
};

export type listTasksResponse = (listTasksResponseSuccess | listTasksResponseError)

export const getListTasksUrl = (params?: ListTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/tasks?${stringifiedParams}` : `/api/tasks`
}

/**
 * Proposto. As tarefas do quadro da empresa ativa. NÃO é `PagedResult`, e é decisão: um quadro kanban mostra as quatro colunas de uma vez e uma página de 10 cortaria coluna no meio, dando contagem de coluna errada. Se o volume crescer, o corte certo é por período/responsável, não por página.
 */
export const listTasks = async (params?: ListTasksParams, options?: Parameters<typeof apiFetch>[1]): Promise<listTasksResponse> => {

  return apiFetch<listTasksResponse>(getListTasksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type createTaskResponse201 = {
  data: TaskDto
  status: 201
}

export type createTaskResponse400 = {
  data: ProblemDetails
  status: 400
}

export type createTaskResponse409 = {
  data: ProblemDetails
  status: 409
}

export type createTaskResponseSuccess = (createTaskResponse201) & {
  headers: Headers;
};
export type createTaskResponseError = (createTaskResponse400 | createTaskResponse409) & {
  headers: Headers;
};

export type createTaskResponse = (createTaskResponseSuccess | createTaskResponseError)

export const getCreateTaskUrl = () => {




  return `/api/tasks`
}

/**
 * Proposto. Cria tarefa no quadro da empresa ativa.
 */
export const createTask = async (taskWriteRequest: TaskWriteRequest, options?: Parameters<typeof apiFetch>[1]): Promise<createTaskResponse> => {

  return apiFetch<createTaskResponse>(getCreateTaskUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(taskWriteRequest)
  }
);}



export type patchTaskResponse200 = {
  data: TaskDto
  status: 200
}

export type patchTaskResponse400 = {
  data: ProblemDetails
  status: 400
}

export type patchTaskResponse404 = {
  data: ProblemDetails
  status: 404
}

export type patchTaskResponseSuccess = (patchTaskResponse200) & {
  headers: Headers;
};
export type patchTaskResponseError = (patchTaskResponse400 | patchTaskResponse404) & {
  headers: Headers;
};

export type patchTaskResponse = (patchTaskResponseSuccess | patchTaskResponseError)

export const getPatchTaskUrl = (taskId: string,) => {




  return `/api/tasks/${taskId}`
}

/**
 * Proposto. Mudança PARCIAL de uma tarefa — é o verbo do quadro: mover de coluna muda `status` e nada mais. É a única exceção ao `PUT` substitui o registro inteiro que vale no resto do contrato, e ela existe porque o cartão do quadro não carrega o registro completo; um `PUT` a partir dele apagaria o que a tela não mostra.
 */
export const patchTask = async (taskId: string,
    taskPatchRequest: TaskPatchRequest, options?: Parameters<typeof apiFetch>[1]): Promise<patchTaskResponse> => {

  return apiFetch<patchTaskResponse>(getPatchTaskUrl(taskId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(taskPatchRequest)
  }
);}



export type listTodosResponse200 = {
  data: TodoDto[]
  status: 200
}

export type listTodosResponseSuccess = (listTodosResponse200) & {
  headers: Headers;
};
;

export type listTodosResponse = (listTodosResponseSuccess)

export const getListTodosUrl = () => {




  return `/api/todos`
}

/**
 * Proposto. A lista A fazer — lembrete curto do OPERADOR na empresa ativa, sem responsável, sem prazo e sem coluna. Recurso separado de `tasks` de propósito: fundir os dois obrigaria todo lembrete a carregar prioridade, prazo e responsável em branco, e a tela teria de adivinhar o que é lembrete e o que é tarefa de quadro.
 */
export const listTodos = async ( options?: Parameters<typeof apiFetch>[1]): Promise<listTodosResponse> => {

  return apiFetch<listTodosResponse>(getListTodosUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type patchTodoResponse200 = {
  data: TodoDto
  status: 200
}

export type patchTodoResponse400 = {
  data: ProblemDetails
  status: 400
}

export type patchTodoResponse404 = {
  data: ProblemDetails
  status: 404
}

export type patchTodoResponseSuccess = (patchTodoResponse200) & {
  headers: Headers;
};
export type patchTodoResponseError = (patchTodoResponse400 | patchTodoResponse404) & {
  headers: Headers;
};

export type patchTodoResponse = (patchTodoResponseSuccess | patchTodoResponseError)

export const getPatchTodoUrl = (todoId: string,) => {




  return `/api/todos/${todoId}`
}

/**
 * Proposto. Marca ou desmarca o item da lista A fazer.
 */
export const patchTodo = async (todoId: string,
    todoPatchRequest: TodoPatchRequest, options?: Parameters<typeof apiFetch>[1]): Promise<patchTodoResponse> => {

  return apiFetch<patchTodoResponse>(getPatchTodoUrl(todoId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(todoPatchRequest)
  }
);}



export type listProjectsResponse200 = {
  data: ProjectDto[]
  status: 200
}

export type listProjectsResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listProjectsResponseSuccess = (listProjectsResponse200) & {
  headers: Headers;
};
export type listProjectsResponseError = (listProjectsResponse400) & {
  headers: Headers;
};

export type listProjectsResponse = (listProjectsResponseSuccess | listProjectsResponseError)

export const getListProjectsUrl = (params?: ListProjectsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/projects?${stringifiedParams}` : `/api/projects`
}

/**
 * Proposto. Projetos da empresa ativa — o que o seletor do Planner lista.
 */
export const listProjects = async (params?: ListProjectsParams, options?: Parameters<typeof apiFetch>[1]): Promise<listProjectsResponse> => {

  return apiFetch<listProjectsResponse>(getListProjectsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type getProjectPlanResponse200 = {
  data: ProjectPlanDto
  status: 200
}

export type getProjectPlanResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getProjectPlanResponseSuccess = (getProjectPlanResponse200) & {
  headers: Headers;
};
export type getProjectPlanResponseError = (getProjectPlanResponse404) & {
  headers: Headers;
};

export type getProjectPlanResponse = (getProjectPlanResponseSuccess | getProjectPlanResponseError)

export const getGetProjectPlanUrl = (projectId: string,) => {




  return `/api/projects/${projectId}/plan`
}

/**
 * Proposto. O plano do projeto: fases e, dentro delas, os itens com data de início e fim — é o que o gantt do Planner desenha. Vem em UMA resposta porque a tela desenha a grade inteira de uma vez; fases e itens em caminhos separados fariam a linha aparecer depois da faixa.
 */
export const getProjectPlan = async (projectId: string, options?: Parameters<typeof apiFetch>[1]): Promise<getProjectPlanResponse> => {

  return apiFetch<getProjectPlanResponse>(getGetProjectPlanUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
);}



export type listEmployeesResponse200 = {
  data: PagedResultOfEmployeeDto
  status: 200
}

export type listEmployeesResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listEmployeesResponseSuccess = (listEmployeesResponse200) & {
  headers: Headers;
};
export type listEmployeesResponseError = (listEmployeesResponse400) & {
  headers: Headers;
};

export type listEmployeesResponse = (listEmployeesResponseSuccess | listEmployeesResponseError)

export const getListEmployeesUrl = (params?: ListEmployeesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/employees?${stringifiedParams}` : `/api/employees`
}

/**
 * Proposto. Colaboradores da empresa ativa. Somente leitura neste corte — é daqui que sai o combo de Consultor(a) do orçamento.
 */
export const listEmployees = async (params?: ListEmployeesParams, options?: Parameters<typeof apiFetch>[1]): Promise<listEmployeesResponse> => {

  return apiFetch<listEmployeesResponse>(getListEmployeesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type listQuotesResponse200 = {
  data: PagedResultOfQuoteDto
  status: 200
}

export type listQuotesResponse400 = {
  data: ProblemDetails
  status: 400
}

export type listQuotesResponseSuccess = (listQuotesResponse200) & {
  headers: Headers;
};
export type listQuotesResponseError = (listQuotesResponse400) & {
  headers: Headers;
};

export type listQuotesResponse = (listQuotesResponseSuccess | listQuotesResponseError)

export const getListQuotesUrl = (params?: ListQuotesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/quotes?${stringifiedParams}` : `/api/quotes`
}

/**
 * Proposto. Orçamentos da empresa ativa. `sortBy` aceita `number`, `issuedAt`, `expiresAt`, `customerName` e `projectName`; fora da lista é 400.
 */
export const listQuotes = async (params?: ListQuotesParams, options?: Parameters<typeof apiFetch>[1]): Promise<listQuotesResponse> => {

  return apiFetch<listQuotesResponse>(getListQuotesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type createQuoteResponse201 = {
  data: QuoteDetailDto
  status: 201
}

export type createQuoteResponse400 = {
  data: ProblemDetails
  status: 400
}

export type createQuoteResponse403 = {
  data: ProblemDetails
  status: 403
}

export type createQuoteResponse409 = {
  data: ProblemDetails
  status: 409
}

export type createQuoteResponseSuccess = (createQuoteResponse201) & {
  headers: Headers;
};
export type createQuoteResponseError = (createQuoteResponse400 | createQuoteResponse403 | createQuoteResponse409) & {
  headers: Headers;
};

export type createQuoteResponse = (createQuoteResponseSuccess | createQuoteResponseError)

export const getCreateQuoteUrl = () => {




  return `/api/quotes`
}

/**
 * Proposto. Cria orçamento na empresa ativa. O número é atribuído aqui.
 */
export const createQuote = async (quoteWriteRequest: QuoteWriteRequest, options?: Parameters<typeof apiFetch>[1]): Promise<createQuoteResponse> => {

  return apiFetch<createQuoteResponse>(getCreateQuoteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(quoteWriteRequest)
  }
);}



export type getQuoteResponse200 = {
  data: QuoteDetailDto
  status: 200
}

export type getQuoteResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getQuoteResponseSuccess = (getQuoteResponse200) & {
  headers: Headers;
};
export type getQuoteResponseError = (getQuoteResponse404) & {
  headers: Headers;
};

export type getQuoteResponse = (getQuoteResponseSuccess | getQuoteResponseError)

export const getGetQuoteUrl = (id: string,) => {




  return `/api/quotes/${id}`
}

/**
 * Proposto. O documento inteiro, com ambientes e itens.
 */
export const getQuote = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<getQuoteResponse> => {

  return apiFetch<getQuoteResponse>(getGetQuoteUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type updateQuoteResponse200 = {
  data: QuoteDetailDto
  status: 200
}

export type updateQuoteResponse400 = {
  data: ProblemDetails
  status: 400
}

export type updateQuoteResponse403 = {
  data: ProblemDetails
  status: 403
}

export type updateQuoteResponse404 = {
  data: ProblemDetails
  status: 404
}

export type updateQuoteResponse409 = {
  data: ProblemDetails
  status: 409
}

export type updateQuoteResponseSuccess = (updateQuoteResponse200) & {
  headers: Headers;
};
export type updateQuoteResponseError = (updateQuoteResponse400 | updateQuoteResponse403 | updateQuoteResponse404 | updateQuoteResponse409) & {
  headers: Headers;
};

export type updateQuoteResponse = (updateQuoteResponseSuccess | updateQuoteResponseError)

export const getUpdateQuoteUrl = (id: string,) => {




  return `/api/quotes/${id}`
}

/**
 * Proposto. Substitui o documento INTEIRO, itens e ambientes junto. Orçamento cancelado não aceita alteração — é 409, não 400.
 */
export const updateQuote = async (id: string,
    quoteWriteRequest: QuoteWriteRequest, options?: Parameters<typeof apiFetch>[1]): Promise<updateQuoteResponse> => {

  return apiFetch<updateQuoteResponse>(getUpdateQuoteUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(quoteWriteRequest)
  }
);}



export type cancelQuoteResponse200 = {
  data: QuoteDetailDto
  status: 200
}

export type cancelQuoteResponse403 = {
  data: ProblemDetails
  status: 403
}

export type cancelQuoteResponse404 = {
  data: ProblemDetails
  status: 404
}

export type cancelQuoteResponse409 = {
  data: ProblemDetails
  status: 409
}

export type cancelQuoteResponseSuccess = (cancelQuoteResponse200) & {
  headers: Headers;
};
export type cancelQuoteResponseError = (cancelQuoteResponse403 | cancelQuoteResponse404 | cancelQuoteResponse409) & {
  headers: Headers;
};

export type cancelQuoteResponse = (cancelQuoteResponseSuccess | cancelQuoteResponseError)

export const getCancelQuoteUrl = (id: string,) => {




  return `/api/quotes/${id}/cancel`
}

/**
 * Proposto. Cancela o orçamento (`status: cancelled`). Documento não se apaga nem se desativa: a listagem continua mostrando, com a situação. Cancelar duas vezes é 409.
 */
export const cancelQuote = async (id: string, options?: Parameters<typeof apiFetch>[1]): Promise<cancelQuoteResponse> => {

  return apiFetch<cancelQuoteResponse>(getCancelQuoteUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




// Anexado por scripts/pos-codegen.mjs: o app importa os tipos dos modelos de '@/api/gerado'.
export * from './index.schemas';
