// @ts-nocheck
/* GERADO por `pnpm codegen` a partir de contracts/openapi-v1.json. NÃO EDITAR.
   `@ts-nocheck` é deliberado: ver scripts/pos-codegen.mjs. */
// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthChangePasswordData, AuthChangePasswordErrors, AuthChangePasswordResponses, AuthLoginData, AuthLoginErrors, AuthLoginResponses, AuthLogoutData, AuthLogoutResponses, AuthMeData, AuthMeResponses, AuthSetActiveTenantData, AuthSetActiveTenantErrors, AuthSetActiveTenantResponses, AuthTenantsData, AuthTenantsResponses, CreatePartnerData, CreatePartnerErrors, CreatePartnerResponses, CreateProductData, CreateProductErrors, CreateProductResponses, GetProductData, GetProductErrors, GetProductResponses, HealthData, HealthDbData, HealthDbErrors, HealthDbResponses, HealthResponses, LinkPartnerData, LinkPartnerErrors, LinkPartnerResponses, ListCatalogLookupsData, ListCatalogLookupsErrors, ListCatalogLookupsResponses, ListPartnersData, ListPartnersErrors, ListPartnersResponses, ListProductsData, ListProductsErrors, ListProductsResponses, UpdatePartnerData, UpdatePartnerErrors, UpdatePartnerResponses, UpdateProductData, UpdateProductErrors, UpdateProductResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

export const healthDb = <ThrowOnError extends boolean = false>(options?: Options<HealthDbData, ThrowOnError>): RequestResult<HealthDbResponses, HealthDbErrors, ThrowOnError> => (options?.client ?? client).get<HealthDbResponses, HealthDbErrors, ThrowOnError>({ url: '/health/db', ...options });

export const listCatalogLookups = <ThrowOnError extends boolean = false>(options?: Options<ListCatalogLookupsData, ThrowOnError>): RequestResult<ListCatalogLookupsResponses, ListCatalogLookupsErrors, ThrowOnError> => (options?.client ?? client).get<ListCatalogLookupsResponses, ListCatalogLookupsErrors, ThrowOnError>({ url: '/api/catalog-lookups', ...options });

export const listProducts = <ThrowOnError extends boolean = false>(options?: Options<ListProductsData, ThrowOnError>): RequestResult<ListProductsResponses, ListProductsErrors, ThrowOnError> => (options?.client ?? client).get<ListProductsResponses, ListProductsErrors, ThrowOnError>({ url: '/api/products', ...options });

export const createProduct = <ThrowOnError extends boolean = false>(options: Options<CreateProductData, ThrowOnError>): RequestResult<CreateProductResponses, CreateProductErrors, ThrowOnError> => (options.client ?? client).post<CreateProductResponses, CreateProductErrors, ThrowOnError>({
    url: '/api/products',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getProduct = <ThrowOnError extends boolean = false>(options: Options<GetProductData, ThrowOnError>): RequestResult<GetProductResponses, GetProductErrors, ThrowOnError> => (options.client ?? client).get<GetProductResponses, GetProductErrors, ThrowOnError>({ url: '/api/products/{id}', ...options });

export const updateProduct = <ThrowOnError extends boolean = false>(options: Options<UpdateProductData, ThrowOnError>): RequestResult<UpdateProductResponses, UpdateProductErrors, ThrowOnError> => (options.client ?? client).put<UpdateProductResponses, UpdateProductErrors, ThrowOnError>({
    url: '/api/products/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listPartners = <ThrowOnError extends boolean = false>(options?: Options<ListPartnersData, ThrowOnError>): RequestResult<ListPartnersResponses, ListPartnersErrors, ThrowOnError> => (options?.client ?? client).get<ListPartnersResponses, ListPartnersErrors, ThrowOnError>({ url: '/api/partners', ...options });

export const createPartner = <ThrowOnError extends boolean = false>(options: Options<CreatePartnerData, ThrowOnError>): RequestResult<CreatePartnerResponses, CreatePartnerErrors, ThrowOnError> => (options.client ?? client).post<CreatePartnerResponses, CreatePartnerErrors, ThrowOnError>({
    url: '/api/partners',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const updatePartner = <ThrowOnError extends boolean = false>(options: Options<UpdatePartnerData, ThrowOnError>): RequestResult<UpdatePartnerResponses, UpdatePartnerErrors, ThrowOnError> => (options.client ?? client).put<UpdatePartnerResponses, UpdatePartnerErrors, ThrowOnError>({
    url: '/api/partners/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const linkPartner = <ThrowOnError extends boolean = false>(options: Options<LinkPartnerData, ThrowOnError>): RequestResult<LinkPartnerResponses, LinkPartnerErrors, ThrowOnError> => (options.client ?? client).post<LinkPartnerResponses, LinkPartnerErrors, ThrowOnError>({
    url: '/api/partners/{id}/link',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authLogin = <ThrowOnError extends boolean = false>(options: Options<AuthLoginData, ThrowOnError>): RequestResult<AuthLoginResponses, AuthLoginErrors, ThrowOnError> => (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthLogoutData, ThrowOnError>): RequestResult<AuthLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<AuthLogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

export const authChangePassword = <ThrowOnError extends boolean = false>(options: Options<AuthChangePasswordData, ThrowOnError>): RequestResult<AuthChangePasswordResponses, AuthChangePasswordErrors, ThrowOnError> => (options.client ?? client).post<AuthChangePasswordResponses, AuthChangePasswordErrors, ThrowOnError>({
    url: '/auth/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authMe = <ThrowOnError extends boolean = false>(options?: Options<AuthMeData, ThrowOnError>): RequestResult<AuthMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<AuthMeResponses, unknown, ThrowOnError>({ url: '/auth/me', ...options });

export const authTenants = <ThrowOnError extends boolean = false>(options?: Options<AuthTenantsData, ThrowOnError>): RequestResult<AuthTenantsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<AuthTenantsResponses, unknown, ThrowOnError>({ url: '/auth/tenants', ...options });

export const authSetActiveTenant = <ThrowOnError extends boolean = false>(options: Options<AuthSetActiveTenantData, ThrowOnError>): RequestResult<AuthSetActiveTenantResponses, AuthSetActiveTenantErrors, ThrowOnError> => (options.client ?? client).put<AuthSetActiveTenantResponses, AuthSetActiveTenantErrors, ThrowOnError>({
    url: '/auth/active-tenant',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
