// @ts-nocheck
/* GERADO por `pnpm codegen` a partir de contracts/openapi-v1.json. NÃO EDITAR.
   `@ts-nocheck` é deliberado: ver scripts/pos-codegen.mjs. */
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CatalogLookupDto = {
    id: string;
    kind: string;
    name: string;
    active: boolean;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type HealthStatus = {
    status: string;
};

export type LoginFalhou = {
    detail: string;
};

export type LoginOk = {
    mustChangePassword: boolean;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type PagedResultOfCatalogLookupDto = {
    rows: Array<CatalogLookupDto>;
    total: number;
};

export type PagedResultOfPartnerDto = {
    rows: Array<PartnerDto>;
    total: number;
};

export type PagedResultOfProductDto = {
    rows: Array<ProductDto>;
    total: number;
};

export type PagedResultOfStockMovementDto = {
    rows: Array<StockMovementDto>;
    total: number;
};

export type PartnerDto = {
    id: string;
    code: null | string;
    legalName: string;
    tradeName: null | string;
    document: null | string;
    email: null | string;
    isCustomer: boolean;
    isSupplier: boolean;
    isProfessional: boolean;
    paymentTerms: null | string;
    active: boolean;
    registrationActive: boolean;
};

export type PartnerLinkRequest = {
    code: null | string;
    paymentTerms: null | string;
    active: null | boolean;
};

export type PartnerWriteRequest = {
    document: null | string;
    legalName: null | string;
    tradeName: null | string;
    email: null | string;
    isCustomer: null | boolean;
    isSupplier: null | boolean;
    isProfessional: null | boolean;
    code: null | string;
    paymentTerms: null | string;
    active: null | boolean;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type ProductDetailDto = {
    id: string;
    code: string;
    description: string;
    active: boolean;
    variants: Array<ProductVariantDto>;
};

export type ProductDto = {
    id: string;
    code: string;
    description: string;
    active: boolean;
};

export type ProductVariantDto = {
    id: string;
    finish: string;
    size: string;
    active: boolean;
    priceCents: null | number;
    stockQty: null | number;
    minStock: null | number;
};

export type ProductWriteRequest = {
    code: null | string;
    description: null | string;
    active: null | boolean;
};

export type ReadinessStatus = {
    status: string;
    detail: null | string;
    pendingMigrations: null | number;
};

export type SessaoAtual = {
    organizationId: string;
    employeeId: string;
    activeTenantId: null | string;
    expiresAt: string;
    mustChangePassword: boolean;
};

export type StockMovementDto = {
    id: string;
    variantId: string;
    delta: number;
    balanceAfter: number;
    reason: string;
    occurredAt: string;
    employeeId: null | string;
};

export type StockMovementRequest = {
    delta: null | number;
    reason: null | string;
};

export type TrocarEmpresaRequest = {
    tenantId: string;
};

export type VariantWriteRequest = {
    finish: null | string;
    size: null | string;
    active: null | boolean;
    priceCents: null | number;
    minStock: null | number;
};

export type VinculoDeEmpresa = {
    tenantId: string;
    name: string;
    role: string;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * OK
     */
    200: HealthStatus;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type HealthDbData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/db';
};

export type HealthDbErrors = {
    /**
     * Service Unavailable
     */
    503: ReadinessStatus;
};

export type HealthDbError = HealthDbErrors[keyof HealthDbErrors];

export type HealthDbResponses = {
    /**
     * OK
     */
    200: ReadinessStatus;
};

export type HealthDbResponse = HealthDbResponses[keyof HealthDbResponses];

export type ListCatalogLookupsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        kind?: string;
        sortBy?: string;
        sortDesc?: boolean;
        page?: number;
        pageSize?: number;
    };
    url: '/api/catalog-lookups';
};

export type ListCatalogLookupsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type ListCatalogLookupsError = ListCatalogLookupsErrors[keyof ListCatalogLookupsErrors];

export type ListCatalogLookupsResponses = {
    /**
     * OK
     */
    200: PagedResultOfCatalogLookupDto;
};

export type ListCatalogLookupsResponse = ListCatalogLookupsResponses[keyof ListCatalogLookupsResponses];

export type ListProductsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        sortBy?: string;
        sortDesc?: boolean;
        page?: number;
        pageSize?: number;
    };
    url: '/api/products';
};

export type ListProductsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type ListProductsError = ListProductsErrors[keyof ListProductsErrors];

export type ListProductsResponses = {
    /**
     * OK
     */
    200: PagedResultOfProductDto;
};

export type ListProductsResponse = ListProductsResponses[keyof ListProductsResponses];

export type CreateProductData = {
    body: ProductWriteRequest;
    path?: never;
    query?: never;
    url: '/api/products';
};

export type CreateProductErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateProductError = CreateProductErrors[keyof CreateProductErrors];

export type CreateProductResponses = {
    /**
     * Created
     */
    201: ProductDto;
};

export type CreateProductResponse = CreateProductResponses[keyof CreateProductResponses];

export type GetProductData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type GetProductErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type GetProductError = GetProductErrors[keyof GetProductErrors];

export type GetProductResponses = {
    /**
     * OK
     */
    200: ProductDetailDto;
};

export type GetProductResponse = GetProductResponses[keyof GetProductResponses];

export type UpdateProductData = {
    body: ProductWriteRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type UpdateProductErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type UpdateProductError = UpdateProductErrors[keyof UpdateProductErrors];

export type UpdateProductResponses = {
    /**
     * OK
     */
    200: ProductDto;
};

export type UpdateProductResponse = UpdateProductResponses[keyof UpdateProductResponses];

export type CreateVariantData = {
    body: VariantWriteRequest;
    path: {
        productId: string;
    };
    query?: never;
    url: '/api/products/{productId}/variants';
};

export type CreateVariantErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateVariantError = CreateVariantErrors[keyof CreateVariantErrors];

export type CreateVariantResponses = {
    /**
     * Created
     */
    201: ProductVariantDto;
};

export type CreateVariantResponse = CreateVariantResponses[keyof CreateVariantResponses];

export type UpdateVariantData = {
    body: VariantWriteRequest;
    path: {
        productId: string;
        id: string;
    };
    query?: never;
    url: '/api/products/{productId}/variants/{id}';
};

export type UpdateVariantErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type UpdateVariantError = UpdateVariantErrors[keyof UpdateVariantErrors];

export type UpdateVariantResponses = {
    /**
     * OK
     */
    200: ProductVariantDto;
};

export type UpdateVariantResponse = UpdateVariantResponses[keyof UpdateVariantResponses];

export type ListPartnersData = {
    body?: never;
    path?: never;
    query?: {
        role?: string;
        q?: string;
        sortBy?: string;
        sortDesc?: boolean;
        page?: number;
        pageSize?: number;
    };
    url: '/api/partners';
};

export type ListPartnersErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type ListPartnersError = ListPartnersErrors[keyof ListPartnersErrors];

export type ListPartnersResponses = {
    /**
     * OK
     */
    200: PagedResultOfPartnerDto;
};

export type ListPartnersResponse = ListPartnersResponses[keyof ListPartnersResponses];

export type CreatePartnerData = {
    body: PartnerWriteRequest;
    path?: never;
    query?: never;
    url: '/api/partners';
};

export type CreatePartnerErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreatePartnerError = CreatePartnerErrors[keyof CreatePartnerErrors];

export type CreatePartnerResponses = {
    /**
     * Created
     */
    201: PartnerDto;
};

export type CreatePartnerResponse = CreatePartnerResponses[keyof CreatePartnerResponses];

export type UpdatePartnerData = {
    body: PartnerWriteRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/partners/{id}';
};

export type UpdatePartnerErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type UpdatePartnerError = UpdatePartnerErrors[keyof UpdatePartnerErrors];

export type UpdatePartnerResponses = {
    /**
     * OK
     */
    200: PartnerDto;
};

export type UpdatePartnerResponse = UpdatePartnerResponses[keyof UpdatePartnerResponses];

export type LinkPartnerData = {
    body?: null | PartnerLinkRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/partners/{id}/link';
};

export type LinkPartnerErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type LinkPartnerError = LinkPartnerErrors[keyof LinkPartnerErrors];

export type LinkPartnerResponses = {
    /**
     * Created
     */
    201: PartnerDto;
};

export type LinkPartnerResponse = LinkPartnerResponses[keyof LinkPartnerResponses];

export type ListStockMovementsData = {
    body?: never;
    path: {
        variantId: string;
    };
    query?: {
        sortBy?: string;
        sortDesc?: boolean;
        page?: number;
        pageSize?: number;
    };
    url: '/api/variants/{variantId}/stock-movements';
};

export type ListStockMovementsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type ListStockMovementsError = ListStockMovementsErrors[keyof ListStockMovementsErrors];

export type ListStockMovementsResponses = {
    /**
     * OK
     */
    200: PagedResultOfStockMovementDto;
};

export type ListStockMovementsResponse = ListStockMovementsResponses[keyof ListStockMovementsResponses];

export type CreateStockMovementData = {
    body: StockMovementRequest;
    path: {
        variantId: string;
    };
    query?: never;
    url: '/api/variants/{variantId}/stock-movements';
};

export type CreateStockMovementErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateStockMovementError = CreateStockMovementErrors[keyof CreateStockMovementErrors];

export type CreateStockMovementResponses = {
    /**
     * Created
     */
    201: StockMovementDto;
};

export type CreateStockMovementResponse = CreateStockMovementResponses[keyof CreateStockMovementResponses];

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: LoginFalhou;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * OK
     */
    200: LoginOk;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type AuthChangePasswordErrors = {
    /**
     * Bad Request
     */
    400: LoginFalhou;
};

export type AuthChangePasswordError = AuthChangePasswordErrors[keyof AuthChangePasswordErrors];

export type AuthChangePasswordResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AuthChangePasswordResponse = AuthChangePasswordResponses[keyof AuthChangePasswordResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeResponses = {
    /**
     * OK
     */
    200: SessaoAtual;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/tenants';
};

export type AuthTenantsResponses = {
    /**
     * OK
     */
    200: Array<VinculoDeEmpresa>;
};

export type AuthTenantsResponse = AuthTenantsResponses[keyof AuthTenantsResponses];

export type AuthSetActiveTenantData = {
    body: TrocarEmpresaRequest;
    path?: never;
    query?: never;
    url: '/auth/active-tenant';
};

export type AuthSetActiveTenantErrors = {
    /**
     * Bad Request
     */
    400: LoginFalhou;
};

export type AuthSetActiveTenantError = AuthSetActiveTenantErrors[keyof AuthSetActiveTenantErrors];

export type AuthSetActiveTenantResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AuthSetActiveTenantResponse = AuthSetActiveTenantResponses[keyof AuthSetActiveTenantResponses];
