/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as CadastrosIndexRouteImport } from './routes/cadastros/index'
import { Route as ComprasIndexRouteImport } from './routes/compras/index'
import { Route as EstoqueIndexRouteImport } from './routes/estoque/index'
import { Route as EstoqueMovimentacaoRouteImport } from './routes/estoque/movimentacao'
import { Route as VendasIndexRouteImport } from './routes/vendas/index'
import { Route as CadastrosClientesIndexRouteImport } from './routes/cadastros/clientes/index'
import { Route as CadastrosClientesClienteIdRouteImport } from './routes/cadastros/clientes/$clienteId'
import { Route as CadastrosColaboradoresIndexRouteImport } from './routes/cadastros/colaboradores/index'
import { Route as CadastrosColaboradoresColaboradorIdRouteImport } from './routes/cadastros/colaboradores/$colaboradorId'
import { Route as CadastrosFornecedoresIndexRouteImport } from './routes/cadastros/fornecedores/index'
import { Route as CadastrosFornecedoresFornecedorIdRouteImport } from './routes/cadastros/fornecedores/$fornecedorId'
import { Route as CadastrosProdutosIndexRouteImport } from './routes/cadastros/produtos/index'
import { Route as CadastrosProdutosProdutoIdRouteImport } from './routes/cadastros/produtos/$produtoId'
import { Route as CadastrosProfissionaisIndexRouteImport } from './routes/cadastros/profissionais/index'
import { Route as CadastrosProfissionaisProfissionalIdRouteImport } from './routes/cadastros/profissionais/$profissionalId'
import { Route as ComprasOrdensIndexRouteImport } from './routes/compras/ordens/index'
import { Route as ComprasOrdensOrdemIdRouteImport } from './routes/compras/ordens/$ordemId'
import { Route as ComprasPedidosIndexRouteImport } from './routes/compras/pedidos/index'
import { Route as ComprasPedidosPedidoIdRouteImport } from './routes/compras/pedidos/$pedidoId'
import { Route as VendasOrcamentosIndexRouteImport } from './routes/vendas/orcamentos/index'
import { Route as VendasOrcamentosOrcamentoIdRouteImport } from './routes/vendas/orcamentos/$orcamentoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosIndexRoute = CadastrosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CadastrosRoute,
} as any)
const ComprasIndexRoute = ComprasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComprasRoute,
} as any)
const EstoqueIndexRoute = EstoqueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueMovimentacaoRoute = EstoqueMovimentacaoRouteImport.update({
  id: '/movimentacao',
  path: '/movimentacao',
  getParentRoute: () => EstoqueRoute,
} as any)
const VendasIndexRoute = VendasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendasRoute,
} as any)
const CadastrosClientesIndexRoute = CadastrosClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => CadastrosRoute,
} as any)
const CadastrosClientesClienteIdRoute =
  CadastrosClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => CadastrosRoute,
  } as any)
const CadastrosColaboradoresIndexRoute =
  CadastrosColaboradoresIndexRouteImport.update({
    id: '/colaboradores/',
    path: '/colaboradores/',
    getParentRoute: () => CadastrosRoute,
  } as any)
const CadastrosColaboradoresColaboradorIdRoute =
  CadastrosColaboradoresColaboradorIdRouteImport.update({
    id: '/colaboradores/$colaboradorId',
    path: '/colaboradores/$colaboradorId',
    getParentRoute: () => CadastrosRoute,
  } as any)
const CadastrosFornecedoresIndexRoute =
  CadastrosFornecedoresIndexRouteImport.update({
    id: '/fornecedores/',
    path: '/fornecedores/',
    getParentRoute: () => CadastrosRoute,
  } as any)
const CadastrosFornecedoresFornecedorIdRoute =
  CadastrosFornecedoresFornecedorIdRouteImport.update({
    id: '/fornecedores/$fornecedorId',
    path: '/fornecedores/$fornecedorId',
    getParentRoute: () => CadastrosRoute,
  } as any)
const CadastrosProdutosIndexRoute = CadastrosProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => CadastrosRoute,
} as any)
const CadastrosProdutosProdutoIdRoute =
  CadastrosProdutosProdutoIdRouteImport.update({
    id: '/produtos/$produtoId',
    path: '/produtos/$produtoId',
    getParentRoute: () => CadastrosRoute,
  } as any)
const CadastrosProfissionaisIndexRoute =
  CadastrosProfissionaisIndexRouteImport.update({
    id: '/profissionais/',
    path: '/profissionais/',
    getParentRoute: () => CadastrosRoute,
  } as any)
const CadastrosProfissionaisProfissionalIdRoute =
  CadastrosProfissionaisProfissionalIdRouteImport.update({
    id: '/profissionais/$profissionalId',
    path: '/profissionais/$profissionalId',
    getParentRoute: () => CadastrosRoute,
  } as any)
const ComprasOrdensIndexRoute = ComprasOrdensIndexRouteImport.update({
  id: '/ordens/',
  path: '/ordens/',
  getParentRoute: () => ComprasRoute,
} as any)
const ComprasOrdensOrdemIdRoute = ComprasOrdensOrdemIdRouteImport.update({
  id: '/ordens/$ordemId',
  path: '/ordens/$ordemId',
  getParentRoute: () => ComprasRoute,
} as any)
const ComprasPedidosIndexRoute = ComprasPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => ComprasRoute,
} as any)
const ComprasPedidosPedidoIdRoute = ComprasPedidosPedidoIdRouteImport.update({
  id: '/pedidos/$pedidoId',
  path: '/pedidos/$pedidoId',
  getParentRoute: () => ComprasRoute,
} as any)
const VendasOrcamentosIndexRoute = VendasOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => VendasRoute,
} as any)
const VendasOrcamentosOrcamentoIdRoute =
  VendasOrcamentosOrcamentoIdRouteImport.update({
    id: '/orcamentos/$orcamentoId',
    path: '/orcamentos/$orcamentoId',
    getParentRoute: () => VendasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRouteWithChildren
  '/compras': typeof ComprasRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/tarefas': typeof TarefasRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/vendas': typeof VendasRouteWithChildren
  '/estoque/movimentacao': typeof EstoqueMovimentacaoRoute
  '/cadastros/': typeof CadastrosIndexRoute
  '/compras/': typeof ComprasIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/vendas/': typeof VendasIndexRoute
  '/cadastros/clientes/$clienteId': typeof CadastrosClientesClienteIdRoute
  '/cadastros/colaboradores/$colaboradorId': typeof CadastrosColaboradoresColaboradorIdRoute
  '/cadastros/fornecedores/$fornecedorId': typeof CadastrosFornecedoresFornecedorIdRoute
  '/cadastros/produtos/$produtoId': typeof CadastrosProdutosProdutoIdRoute
  '/cadastros/profissionais/$profissionalId': typeof CadastrosProfissionaisProfissionalIdRoute
  '/compras/ordens/$ordemId': typeof ComprasOrdensOrdemIdRoute
  '/compras/pedidos/$pedidoId': typeof ComprasPedidosPedidoIdRoute
  '/vendas/orcamentos/$orcamentoId': typeof VendasOrcamentosOrcamentoIdRoute
  '/cadastros/clientes/': typeof CadastrosClientesIndexRoute
  '/cadastros/colaboradores/': typeof CadastrosColaboradoresIndexRoute
  '/cadastros/fornecedores/': typeof CadastrosFornecedoresIndexRoute
  '/cadastros/produtos/': typeof CadastrosProdutosIndexRoute
  '/cadastros/profissionais/': typeof CadastrosProfissionaisIndexRoute
  '/compras/ordens/': typeof ComprasOrdensIndexRoute
  '/compras/pedidos/': typeof ComprasPedidosIndexRoute
  '/vendas/orcamentos/': typeof VendasOrcamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/tarefas': typeof TarefasRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/estoque/movimentacao': typeof EstoqueMovimentacaoRoute
  '/cadastros': typeof CadastrosIndexRoute
  '/compras': typeof ComprasIndexRoute
  '/estoque': typeof EstoqueIndexRoute
  '/vendas': typeof VendasIndexRoute
  '/cadastros/clientes/$clienteId': typeof CadastrosClientesClienteIdRoute
  '/cadastros/colaboradores/$colaboradorId': typeof CadastrosColaboradoresColaboradorIdRoute
  '/cadastros/fornecedores/$fornecedorId': typeof CadastrosFornecedoresFornecedorIdRoute
  '/cadastros/produtos/$produtoId': typeof CadastrosProdutosProdutoIdRoute
  '/cadastros/profissionais/$profissionalId': typeof CadastrosProfissionaisProfissionalIdRoute
  '/compras/ordens/$ordemId': typeof ComprasOrdensOrdemIdRoute
  '/compras/pedidos/$pedidoId': typeof ComprasPedidosPedidoIdRoute
  '/vendas/orcamentos/$orcamentoId': typeof VendasOrcamentosOrcamentoIdRoute
  '/cadastros/clientes': typeof CadastrosClientesIndexRoute
  '/cadastros/colaboradores': typeof CadastrosColaboradoresIndexRoute
  '/cadastros/fornecedores': typeof CadastrosFornecedoresIndexRoute
  '/cadastros/produtos': typeof CadastrosProdutosIndexRoute
  '/cadastros/profissionais': typeof CadastrosProfissionaisIndexRoute
  '/compras/ordens': typeof ComprasOrdensIndexRoute
  '/compras/pedidos': typeof ComprasPedidosIndexRoute
  '/vendas/orcamentos': typeof VendasOrcamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRouteWithChildren
  '/compras': typeof ComprasRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/tarefas': typeof TarefasRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/vendas': typeof VendasRouteWithChildren
  '/estoque/movimentacao': typeof EstoqueMovimentacaoRoute
  '/cadastros/': typeof CadastrosIndexRoute
  '/compras/': typeof ComprasIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/vendas/': typeof VendasIndexRoute
  '/cadastros/clientes/$clienteId': typeof CadastrosClientesClienteIdRoute
  '/cadastros/colaboradores/$colaboradorId': typeof CadastrosColaboradoresColaboradorIdRoute
  '/cadastros/fornecedores/$fornecedorId': typeof CadastrosFornecedoresFornecedorIdRoute
  '/cadastros/produtos/$produtoId': typeof CadastrosProdutosProdutoIdRoute
  '/cadastros/profissionais/$profissionalId': typeof CadastrosProfissionaisProfissionalIdRoute
  '/compras/ordens/$ordemId': typeof ComprasOrdensOrdemIdRoute
  '/compras/pedidos/$pedidoId': typeof ComprasPedidosPedidoIdRoute
  '/vendas/orcamentos/$orcamentoId': typeof VendasOrcamentosOrcamentoIdRoute
  '/cadastros/clientes/': typeof CadastrosClientesIndexRoute
  '/cadastros/colaboradores/': typeof CadastrosColaboradoresIndexRoute
  '/cadastros/fornecedores/': typeof CadastrosFornecedoresIndexRoute
  '/cadastros/produtos/': typeof CadastrosProdutosIndexRoute
  '/cadastros/profissionais/': typeof CadastrosProfissionaisIndexRoute
  '/compras/ordens/': typeof ComprasOrdensIndexRoute
  '/compras/pedidos/': typeof ComprasPedidosIndexRoute
  '/vendas/orcamentos/': typeof VendasOrcamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastros'
    | '/compras'
    | '/dashboard'
    | '/estoque'
    | '/login'
    | '/planner'
    | '/tarefas'
    | '/trocar-senha'
    | '/vendas'
    | '/estoque/movimentacao'
    | '/cadastros/'
    | '/compras/'
    | '/estoque/'
    | '/vendas/'
    | '/cadastros/clientes/$clienteId'
    | '/cadastros/colaboradores/$colaboradorId'
    | '/cadastros/fornecedores/$fornecedorId'
    | '/cadastros/produtos/$produtoId'
    | '/cadastros/profissionais/$profissionalId'
    | '/compras/ordens/$ordemId'
    | '/compras/pedidos/$pedidoId'
    | '/vendas/orcamentos/$orcamentoId'
    | '/cadastros/clientes/'
    | '/cadastros/colaboradores/'
    | '/cadastros/fornecedores/'
    | '/cadastros/produtos/'
    | '/cadastros/profissionais/'
    | '/compras/ordens/'
    | '/compras/pedidos/'
    | '/vendas/orcamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/planner'
    | '/tarefas'
    | '/trocar-senha'
    | '/estoque/movimentacao'
    | '/cadastros'
    | '/compras'
    | '/estoque'
    | '/vendas'
    | '/cadastros/clientes/$clienteId'
    | '/cadastros/colaboradores/$colaboradorId'
    | '/cadastros/fornecedores/$fornecedorId'
    | '/cadastros/produtos/$produtoId'
    | '/cadastros/profissionais/$profissionalId'
    | '/compras/ordens/$ordemId'
    | '/compras/pedidos/$pedidoId'
    | '/vendas/orcamentos/$orcamentoId'
    | '/cadastros/clientes'
    | '/cadastros/colaboradores'
    | '/cadastros/fornecedores'
    | '/cadastros/produtos'
    | '/cadastros/profissionais'
    | '/compras/ordens'
    | '/compras/pedidos'
    | '/vendas/orcamentos'
  id:
    | '__root__'
    | '/'
    | '/cadastros'
    | '/compras'
    | '/dashboard'
    | '/estoque'
    | '/login'
    | '/planner'
    | '/tarefas'
    | '/trocar-senha'
    | '/vendas'
    | '/estoque/movimentacao'
    | '/cadastros/'
    | '/compras/'
    | '/estoque/'
    | '/vendas/'
    | '/cadastros/clientes/$clienteId'
    | '/cadastros/colaboradores/$colaboradorId'
    | '/cadastros/fornecedores/$fornecedorId'
    | '/cadastros/produtos/$produtoId'
    | '/cadastros/profissionais/$profissionalId'
    | '/compras/ordens/$ordemId'
    | '/compras/pedidos/$pedidoId'
    | '/vendas/orcamentos/$orcamentoId'
    | '/cadastros/clientes/'
    | '/cadastros/colaboradores/'
    | '/cadastros/fornecedores/'
    | '/cadastros/produtos/'
    | '/cadastros/profissionais/'
    | '/compras/ordens/'
    | '/compras/pedidos/'
    | '/vendas/orcamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrosRoute: typeof CadastrosRouteWithChildren
  ComprasRoute: typeof ComprasRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EstoqueRoute: typeof EstoqueRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlannerRoute: typeof PlannerRoute
  TarefasRoute: typeof TarefasRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  VendasRoute: typeof VendasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/': {
      id: '/cadastros/'
      path: '/'
      fullPath: '/cadastros/'
      preLoaderRoute: typeof CadastrosIndexRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/compras/': {
      id: '/compras/'
      path: '/'
      fullPath: '/compras/'
      preLoaderRoute: typeof ComprasIndexRouteImport
      parentRoute: typeof ComprasRoute
    }
    '/estoque/': {
      id: '/estoque/'
      path: '/'
      fullPath: '/estoque/'
      preLoaderRoute: typeof EstoqueIndexRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/movimentacao': {
      id: '/estoque/movimentacao'
      path: '/movimentacao'
      fullPath: '/estoque/movimentacao'
      preLoaderRoute: typeof EstoqueMovimentacaoRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/vendas/': {
      id: '/vendas/'
      path: '/'
      fullPath: '/vendas/'
      preLoaderRoute: typeof VendasIndexRouteImport
      parentRoute: typeof VendasRoute
    }
    '/cadastros/clientes/': {
      id: '/cadastros/clientes/'
      path: '/clientes'
      fullPath: '/cadastros/clientes/'
      preLoaderRoute: typeof CadastrosClientesIndexRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/clientes/$clienteId': {
      id: '/cadastros/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/cadastros/clientes/$clienteId'
      preLoaderRoute: typeof CadastrosClientesClienteIdRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/colaboradores/': {
      id: '/cadastros/colaboradores/'
      path: '/colaboradores'
      fullPath: '/cadastros/colaboradores/'
      preLoaderRoute: typeof CadastrosColaboradoresIndexRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/colaboradores/$colaboradorId': {
      id: '/cadastros/colaboradores/$colaboradorId'
      path: '/colaboradores/$colaboradorId'
      fullPath: '/cadastros/colaboradores/$colaboradorId'
      preLoaderRoute: typeof CadastrosColaboradoresColaboradorIdRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/fornecedores/': {
      id: '/cadastros/fornecedores/'
      path: '/fornecedores'
      fullPath: '/cadastros/fornecedores/'
      preLoaderRoute: typeof CadastrosFornecedoresIndexRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/fornecedores/$fornecedorId': {
      id: '/cadastros/fornecedores/$fornecedorId'
      path: '/fornecedores/$fornecedorId'
      fullPath: '/cadastros/fornecedores/$fornecedorId'
      preLoaderRoute: typeof CadastrosFornecedoresFornecedorIdRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/produtos/': {
      id: '/cadastros/produtos/'
      path: '/produtos'
      fullPath: '/cadastros/produtos/'
      preLoaderRoute: typeof CadastrosProdutosIndexRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/produtos/$produtoId': {
      id: '/cadastros/produtos/$produtoId'
      path: '/produtos/$produtoId'
      fullPath: '/cadastros/produtos/$produtoId'
      preLoaderRoute: typeof CadastrosProdutosProdutoIdRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/profissionais/': {
      id: '/cadastros/profissionais/'
      path: '/profissionais'
      fullPath: '/cadastros/profissionais/'
      preLoaderRoute: typeof CadastrosProfissionaisIndexRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/profissionais/$profissionalId': {
      id: '/cadastros/profissionais/$profissionalId'
      path: '/profissionais/$profissionalId'
      fullPath: '/cadastros/profissionais/$profissionalId'
      preLoaderRoute: typeof CadastrosProfissionaisProfissionalIdRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/compras/ordens/': {
      id: '/compras/ordens/'
      path: '/ordens'
      fullPath: '/compras/ordens/'
      preLoaderRoute: typeof ComprasOrdensIndexRouteImport
      parentRoute: typeof ComprasRoute
    }
    '/compras/ordens/$ordemId': {
      id: '/compras/ordens/$ordemId'
      path: '/ordens/$ordemId'
      fullPath: '/compras/ordens/$ordemId'
      preLoaderRoute: typeof ComprasOrdensOrdemIdRouteImport
      parentRoute: typeof ComprasRoute
    }
    '/compras/pedidos/': {
      id: '/compras/pedidos/'
      path: '/pedidos'
      fullPath: '/compras/pedidos/'
      preLoaderRoute: typeof ComprasPedidosIndexRouteImport
      parentRoute: typeof ComprasRoute
    }
    '/compras/pedidos/$pedidoId': {
      id: '/compras/pedidos/$pedidoId'
      path: '/pedidos/$pedidoId'
      fullPath: '/compras/pedidos/$pedidoId'
      preLoaderRoute: typeof ComprasPedidosPedidoIdRouteImport
      parentRoute: typeof ComprasRoute
    }
    '/vendas/orcamentos/': {
      id: '/vendas/orcamentos/'
      path: '/orcamentos'
      fullPath: '/vendas/orcamentos/'
      preLoaderRoute: typeof VendasOrcamentosIndexRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/orcamentos/$orcamentoId': {
      id: '/vendas/orcamentos/$orcamentoId'
      path: '/orcamentos/$orcamentoId'
      fullPath: '/vendas/orcamentos/$orcamentoId'
      preLoaderRoute: typeof VendasOrcamentosOrcamentoIdRouteImport
      parentRoute: typeof VendasRoute
    }
  }
}

interface CadastrosRouteChildren {
  CadastrosIndexRoute: typeof CadastrosIndexRoute
  CadastrosClientesClienteIdRoute: typeof CadastrosClientesClienteIdRoute
  CadastrosColaboradoresColaboradorIdRoute: typeof CadastrosColaboradoresColaboradorIdRoute
  CadastrosFornecedoresFornecedorIdRoute: typeof CadastrosFornecedoresFornecedorIdRoute
  CadastrosProdutosProdutoIdRoute: typeof CadastrosProdutosProdutoIdRoute
  CadastrosProfissionaisProfissionalIdRoute: typeof CadastrosProfissionaisProfissionalIdRoute
  CadastrosClientesIndexRoute: typeof CadastrosClientesIndexRoute
  CadastrosColaboradoresIndexRoute: typeof CadastrosColaboradoresIndexRoute
  CadastrosFornecedoresIndexRoute: typeof CadastrosFornecedoresIndexRoute
  CadastrosProdutosIndexRoute: typeof CadastrosProdutosIndexRoute
  CadastrosProfissionaisIndexRoute: typeof CadastrosProfissionaisIndexRoute
}

const CadastrosRouteChildren: CadastrosRouteChildren = {
  CadastrosIndexRoute: CadastrosIndexRoute,
  CadastrosClientesClienteIdRoute: CadastrosClientesClienteIdRoute,
  CadastrosColaboradoresColaboradorIdRoute:
    CadastrosColaboradoresColaboradorIdRoute,
  CadastrosFornecedoresFornecedorIdRoute:
    CadastrosFornecedoresFornecedorIdRoute,
  CadastrosProdutosProdutoIdRoute: CadastrosProdutosProdutoIdRoute,
  CadastrosProfissionaisProfissionalIdRoute:
    CadastrosProfissionaisProfissionalIdRoute,
  CadastrosClientesIndexRoute: CadastrosClientesIndexRoute,
  CadastrosColaboradoresIndexRoute: CadastrosColaboradoresIndexRoute,
  CadastrosFornecedoresIndexRoute: CadastrosFornecedoresIndexRoute,
  CadastrosProdutosIndexRoute: CadastrosProdutosIndexRoute,
  CadastrosProfissionaisIndexRoute: CadastrosProfissionaisIndexRoute,
}

const CadastrosRouteWithChildren = CadastrosRoute._addFileChildren(
  CadastrosRouteChildren,
)

interface ComprasRouteChildren {
  ComprasIndexRoute: typeof ComprasIndexRoute
  ComprasOrdensOrdemIdRoute: typeof ComprasOrdensOrdemIdRoute
  ComprasPedidosPedidoIdRoute: typeof ComprasPedidosPedidoIdRoute
  ComprasOrdensIndexRoute: typeof ComprasOrdensIndexRoute
  ComprasPedidosIndexRoute: typeof ComprasPedidosIndexRoute
}

const ComprasRouteChildren: ComprasRouteChildren = {
  ComprasIndexRoute: ComprasIndexRoute,
  ComprasOrdensOrdemIdRoute: ComprasOrdensOrdemIdRoute,
  ComprasPedidosPedidoIdRoute: ComprasPedidosPedidoIdRoute,
  ComprasOrdensIndexRoute: ComprasOrdensIndexRoute,
  ComprasPedidosIndexRoute: ComprasPedidosIndexRoute,
}

const ComprasRouteWithChildren =
  ComprasRoute._addFileChildren(ComprasRouteChildren)

interface EstoqueRouteChildren {
  EstoqueMovimentacaoRoute: typeof EstoqueMovimentacaoRoute
  EstoqueIndexRoute: typeof EstoqueIndexRoute
}

const EstoqueRouteChildren: EstoqueRouteChildren = {
  EstoqueMovimentacaoRoute: EstoqueMovimentacaoRoute,
  EstoqueIndexRoute: EstoqueIndexRoute,
}

const EstoqueRouteWithChildren =
  EstoqueRoute._addFileChildren(EstoqueRouteChildren)

interface VendasRouteChildren {
  VendasIndexRoute: typeof VendasIndexRoute
  VendasOrcamentosOrcamentoIdRoute: typeof VendasOrcamentosOrcamentoIdRoute
  VendasOrcamentosIndexRoute: typeof VendasOrcamentosIndexRoute
}

const VendasRouteChildren: VendasRouteChildren = {
  VendasIndexRoute: VendasIndexRoute,
  VendasOrcamentosOrcamentoIdRoute: VendasOrcamentosOrcamentoIdRoute,
  VendasOrcamentosIndexRoute: VendasOrcamentosIndexRoute,
}

const VendasRouteWithChildren =
  VendasRoute._addFileChildren(VendasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrosRoute: CadastrosRouteWithChildren,
  ComprasRoute: ComprasRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EstoqueRoute: EstoqueRouteWithChildren,
  LoginRoute: LoginRoute,
  PlannerRoute: PlannerRoute,
  TarefasRoute: TarefasRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  VendasRoute: VendasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
