/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as CadastrosIndexRouteImport } from './routes/cadastros/index'
import { Route as ComprasIndexRouteImport } from './routes/compras/index'
import { Route as EstoqueIndexRouteImport } from './routes/estoque/index'
import { Route as VendasIndexRouteImport } from './routes/vendas/index'
import { Route as CadastrosClientesIndexRouteImport } from './routes/cadastros/clientes/index'
import { Route as CadastrosClientesClienteIdRouteImport } from './routes/cadastros/clientes/$clienteId'
import { Route as CadastrosFornecedoresIndexRouteImport } from './routes/cadastros/fornecedores/index'
import { Route as CadastrosFornecedoresFornecedorIdRouteImport } from './routes/cadastros/fornecedores/$fornecedorId'
import { Route as CadastrosProdutosIndexRouteImport } from './routes/cadastros/produtos/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosIndexRoute = CadastrosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CadastrosRoute,
} as any)
const ComprasIndexRoute = ComprasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComprasRoute,
} as any)
const EstoqueIndexRoute = EstoqueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstoqueRoute,
} as any)
const VendasIndexRoute = VendasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendasRoute,
} as any)
const CadastrosClientesIndexRoute = CadastrosClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => CadastrosRoute,
} as any)
const CadastrosClientesClienteIdRoute =
  CadastrosClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => CadastrosRoute,
  } as any)
const CadastrosFornecedoresIndexRoute =
  CadastrosFornecedoresIndexRouteImport.update({
    id: '/fornecedores/',
    path: '/fornecedores/',
    getParentRoute: () => CadastrosRoute,
  } as any)
const CadastrosFornecedoresFornecedorIdRoute =
  CadastrosFornecedoresFornecedorIdRouteImport.update({
    id: '/fornecedores/$fornecedorId',
    path: '/fornecedores/$fornecedorId',
    getParentRoute: () => CadastrosRoute,
  } as any)
const CadastrosProdutosIndexRoute = CadastrosProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => CadastrosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRouteWithChildren
  '/compras': typeof ComprasRouteWithChildren
  '/estoque': typeof EstoqueRouteWithChildren
  '/vendas': typeof VendasRouteWithChildren
  '/cadastros/': typeof CadastrosIndexRoute
  '/compras/': typeof ComprasIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/vendas/': typeof VendasIndexRoute
  '/cadastros/clientes/$clienteId': typeof CadastrosClientesClienteIdRoute
  '/cadastros/fornecedores/$fornecedorId': typeof CadastrosFornecedoresFornecedorIdRoute
  '/cadastros/clientes/': typeof CadastrosClientesIndexRoute
  '/cadastros/fornecedores/': typeof CadastrosFornecedoresIndexRoute
  '/cadastros/produtos/': typeof CadastrosProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosIndexRoute
  '/compras': typeof ComprasIndexRoute
  '/estoque': typeof EstoqueIndexRoute
  '/vendas': typeof VendasIndexRoute
  '/cadastros/clientes/$clienteId': typeof CadastrosClientesClienteIdRoute
  '/cadastros/fornecedores/$fornecedorId': typeof CadastrosFornecedoresFornecedorIdRoute
  '/cadastros/clientes': typeof CadastrosClientesIndexRoute
  '/cadastros/fornecedores': typeof CadastrosFornecedoresIndexRoute
  '/cadastros/produtos': typeof CadastrosProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRouteWithChildren
  '/compras': typeof ComprasRouteWithChildren
  '/estoque': typeof EstoqueRouteWithChildren
  '/vendas': typeof VendasRouteWithChildren
  '/cadastros/': typeof CadastrosIndexRoute
  '/compras/': typeof ComprasIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/vendas/': typeof VendasIndexRoute
  '/cadastros/clientes/$clienteId': typeof CadastrosClientesClienteIdRoute
  '/cadastros/fornecedores/$fornecedorId': typeof CadastrosFornecedoresFornecedorIdRoute
  '/cadastros/clientes/': typeof CadastrosClientesIndexRoute
  '/cadastros/fornecedores/': typeof CadastrosFornecedoresIndexRoute
  '/cadastros/produtos/': typeof CadastrosProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastros'
    | '/compras'
    | '/estoque'
    | '/vendas'
    | '/cadastros/'
    | '/compras/'
    | '/estoque/'
    | '/vendas/'
    | '/cadastros/clientes/$clienteId'
    | '/cadastros/fornecedores/$fornecedorId'
    | '/cadastros/clientes/'
    | '/cadastros/fornecedores/'
    | '/cadastros/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastros'
    | '/compras'
    | '/estoque'
    | '/vendas'
    | '/cadastros/clientes/$clienteId'
    | '/cadastros/fornecedores/$fornecedorId'
    | '/cadastros/clientes'
    | '/cadastros/fornecedores'
    | '/cadastros/produtos'
  id:
    | '__root__'
    | '/'
    | '/cadastros'
    | '/compras'
    | '/estoque'
    | '/vendas'
    | '/cadastros/'
    | '/compras/'
    | '/estoque/'
    | '/vendas/'
    | '/cadastros/clientes/$clienteId'
    | '/cadastros/fornecedores/$fornecedorId'
    | '/cadastros/clientes/'
    | '/cadastros/fornecedores/'
    | '/cadastros/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrosRoute: typeof CadastrosRouteWithChildren
  ComprasRoute: typeof ComprasRouteWithChildren
  EstoqueRoute: typeof EstoqueRouteWithChildren
  VendasRoute: typeof VendasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/': {
      id: '/cadastros/'
      path: '/'
      fullPath: '/cadastros/'
      preLoaderRoute: typeof CadastrosIndexRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/compras/': {
      id: '/compras/'
      path: '/'
      fullPath: '/compras/'
      preLoaderRoute: typeof ComprasIndexRouteImport
      parentRoute: typeof ComprasRoute
    }
    '/estoque/': {
      id: '/estoque/'
      path: '/'
      fullPath: '/estoque/'
      preLoaderRoute: typeof EstoqueIndexRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/vendas/': {
      id: '/vendas/'
      path: '/'
      fullPath: '/vendas/'
      preLoaderRoute: typeof VendasIndexRouteImport
      parentRoute: typeof VendasRoute
    }
    '/cadastros/clientes/': {
      id: '/cadastros/clientes/'
      path: '/clientes'
      fullPath: '/cadastros/clientes/'
      preLoaderRoute: typeof CadastrosClientesIndexRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/clientes/$clienteId': {
      id: '/cadastros/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/cadastros/clientes/$clienteId'
      preLoaderRoute: typeof CadastrosClientesClienteIdRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/fornecedores/': {
      id: '/cadastros/fornecedores/'
      path: '/fornecedores'
      fullPath: '/cadastros/fornecedores/'
      preLoaderRoute: typeof CadastrosFornecedoresIndexRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/fornecedores/$fornecedorId': {
      id: '/cadastros/fornecedores/$fornecedorId'
      path: '/fornecedores/$fornecedorId'
      fullPath: '/cadastros/fornecedores/$fornecedorId'
      preLoaderRoute: typeof CadastrosFornecedoresFornecedorIdRouteImport
      parentRoute: typeof CadastrosRoute
    }
    '/cadastros/produtos/': {
      id: '/cadastros/produtos/'
      path: '/produtos'
      fullPath: '/cadastros/produtos/'
      preLoaderRoute: typeof CadastrosProdutosIndexRouteImport
      parentRoute: typeof CadastrosRoute
    }
  }
}

interface CadastrosRouteChildren {
  CadastrosIndexRoute: typeof CadastrosIndexRoute
  CadastrosClientesClienteIdRoute: typeof CadastrosClientesClienteIdRoute
  CadastrosFornecedoresFornecedorIdRoute: typeof CadastrosFornecedoresFornecedorIdRoute
  CadastrosClientesIndexRoute: typeof CadastrosClientesIndexRoute
  CadastrosFornecedoresIndexRoute: typeof CadastrosFornecedoresIndexRoute
  CadastrosProdutosIndexRoute: typeof CadastrosProdutosIndexRoute
}

const CadastrosRouteChildren: CadastrosRouteChildren = {
  CadastrosIndexRoute: CadastrosIndexRoute,
  CadastrosClientesClienteIdRoute: CadastrosClientesClienteIdRoute,
  CadastrosFornecedoresFornecedorIdRoute:
    CadastrosFornecedoresFornecedorIdRoute,
  CadastrosClientesIndexRoute: CadastrosClientesIndexRoute,
  CadastrosFornecedoresIndexRoute: CadastrosFornecedoresIndexRoute,
  CadastrosProdutosIndexRoute: CadastrosProdutosIndexRoute,
}

const CadastrosRouteWithChildren = CadastrosRoute._addFileChildren(
  CadastrosRouteChildren,
)

interface ComprasRouteChildren {
  ComprasIndexRoute: typeof ComprasIndexRoute
}

const ComprasRouteChildren: ComprasRouteChildren = {
  ComprasIndexRoute: ComprasIndexRoute,
}

const ComprasRouteWithChildren =
  ComprasRoute._addFileChildren(ComprasRouteChildren)

interface EstoqueRouteChildren {
  EstoqueIndexRoute: typeof EstoqueIndexRoute
}

const EstoqueRouteChildren: EstoqueRouteChildren = {
  EstoqueIndexRoute: EstoqueIndexRoute,
}

const EstoqueRouteWithChildren =
  EstoqueRoute._addFileChildren(EstoqueRouteChildren)

interface VendasRouteChildren {
  VendasIndexRoute: typeof VendasIndexRoute
}

const VendasRouteChildren: VendasRouteChildren = {
  VendasIndexRoute: VendasIndexRoute,
}

const VendasRouteWithChildren =
  VendasRoute._addFileChildren(VendasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrosRoute: CadastrosRouteWithChildren,
  ComprasRoute: ComprasRouteWithChildren,
  EstoqueRoute: EstoqueRouteWithChildren,
  VendasRoute: VendasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
